-- translation for JXTP Package

return {
	["JXTP"] = "十周年界限突破",
	["JXTP2"] = "十周年界限突破2",
	
	["tenyear_sunquan"] = "界孙权",
	["illustrator:tenyear_sunquan"] = "凝聚永恒",
	["tenyearzhiheng"] = "制衡",
	[":tenyearzhiheng"] = "出牌阶段限一次，你可以弃置任意张牌，然后摸等量的牌。若你以此法弃置了所有手牌，你额外摸一张牌。",
	["tenyearjiuyuan"] = "救援",
	[":tenyearjiuyuan"] = "主公技，其他吴势力角色对自己使用【桃】时，若其体力值大于你，该角色可以改为令你回复1点体力，然后其摸一张牌。",
	["@tenyearjiuyuan-invoke"] = "你可以发动“救援”",
	
	["tenyear_sunshangxiang"] = "界孙尚香",
	["illustrator:tenyear_sunshangxiang"] = "Thinking",
	["tenyearjieyin"] = "结姻",
	[":tenyearjieyin"] = "出牌阶段限一次，你可以选择一名男性角色并弃置一张手牌或将一张装备牌置入其装备区：你与其体力值较高的角色摸一张牌，体力值较低的角色回复1点体力。",
	
	["tenyear_liubei"] = "界刘备",
	["illustrator:tenyear_liubei"] = "木美人",
	["tenyearrende"] = "仁德",
	[":tenyearrende"] = "<font color=\"green\"><b>出牌阶段每名角色限一次，</b></font>你可以将任意张手牌交给一名其他角色。当你给出第二张“仁德”牌时，你可以视为使用一张基本牌。",
	["@tenyearrende-basic"] = "你可以视为使用一张基本牌",
	["@tenyearrende"] = "请选择 【%src】 的目标",
	["tenyearrende:tenyearrende"] = "你是否视为使用【%src】?",
	["~tenyearrende"] = "选择目标角色→点“确定”",
	
	["tenyear_guanyu"] = "界关羽",
	["illustrator:tenyear_guanyu"] = "俊西JUNC",
	["tenyearwusheng"] = "武圣",
	[":tenyearwusheng"] = "你可以将一张红色牌当【杀】使用或打出；你使用的方块【杀】不受攻击范围限制。",
	["tenyearyijue"] = "义绝",
	[":tenyearyijue"] = "出牌阶段限一次，你可以弃置一张牌并令一名其他角色展示一张手牌。若此牌为黑色，其本回合非锁定技失效且不能使用或打出手牌，你对其使用的红桃【杀】伤害+1；"..
					"若此牌为红色，则你获得之，然后你可令该角色回复1点体力。",
	["#TenyearyijueBuff"] = "%from 的“<font color=\"yellow\"><b>义绝</b></font>”被触发，对 %to 的伤害从 %arg 点增加至 %arg2 点",
	["tenyearyijue:recover"] = "你是否令 %src 回复1点体力？",
	
	["tenyear_zhangfei"] = "界张飞",
	["tenyearpaoxiao"] = "咆哮",
	["illustrator:tenyear_zhangfei"] = "SONGQIJIN",
	[":tenyearpaoxiao"] = "锁定技，你使用【杀】无次数限制。若你于出牌阶段内使用过【杀】，你于此阶段使用【杀】无距离限制。",
	["tenyeartishen"] = "替身",
	[":tenyeartishen"] = "出牌阶段结束时，你可以弃置所有锦囊牌和坐骑牌，然后直到你下回合开始，获得所有以你为目标且未对你造成伤害的【杀】。",
	
	["tenyear_zhugeliang"] = "界诸葛亮",
	["illustrator:tenyear_zhugeliang"] = "黑桃J＆Thinking",
	["tenyearguanxing"] = "观星",
	[":tenyearguanxing"] = "准备阶段开始时，你可以观看牌堆顶的五张牌（存活人数小于四时改为三张），然后以任意顺序放回牌堆顶或牌堆底。若你将这些牌均放至牌堆底，本回合结束阶段开始时，你"..
							"可以再进行一次“观星”。",
	
	["tenyear_zhaoyun"] = "界赵云",
	["illustrator:tenyear_zhaoyun"] = "DH",
	["tenyearyajiao"] = "涯角",
	[":tenyearyajiao"] = "当你于回合外使用或打出手牌时，你可以展示牌堆顶一张牌并将其交给任意一名角色。若这两张牌类别不同，你弃置一张牌。",
	["@tenyearyajiao-give"] = "请选择一名角色，其获得 %arg[%arg2]",
	
	["tenyear_huangyueying"] = "界黄月英",
	["illustrator:tenyear_huangyueying"] = "Ask",
	["tenyearjizhi"] = "集智",
	[":tenyearjizhi"] = "当你使用一张锦囊牌时，你可以摸一张牌。若此牌是基本牌，你可以弃置此牌然后本回合手牌上限+1。",
	["tenyearjizhi_discard:discard"] = "你是否弃置此牌令本回合手牌上限+1？",
	
	["tenyear_caocao"] = "界曹操",
	["illustrator:tenyear_caocao"] = "青骑士",
	["tenyearjianxiong"] = "奸雄",
	[":tenyearjianxiong"] = "当你受到伤害后，你可以摸一张牌，然后获得造成此伤害的牌。",
	
	["tenyear_xiahoudun"] = "界夏侯惇",
	["illustrator:tenyear_xiahoudun"] = "DH",
	["tenyearqingjian"] = "清俭",
	[":tenyearqingjian"] = "每个回合限一次，当你在摸牌阶段外获得牌后，你可以展示任意张牌并交给一名其他角色，你给出的牌每有一种类别，当前回合角色本回合手牌上限+1。",
	["@tenyearqingjian"] = "你可以展示任意张牌并交给一名其他角色",
	["~tenyearqingjian"] = "选择若干张牌和一名其他角色→点“确定”",
	
	["tenyear_xuchu"] = "界许褚",
	["illustrator:tenyear_xuchu"] = "巴萨小马",
	["tenyearluoyi"] = "裸衣",
	[":tenyearluoyi"] = "摸牌阶段开始时，你亮出牌堆顶三张牌，然后你可以获得其中的基本牌、武器牌或【决斗】。若如此做，你放弃摸牌，且你为伤害来源的【杀】或【决斗】造成的伤害"..
						"+1直到你的下回合开始。",
	
	["tenyear_guojia"] = "界郭嘉",
	["illustrator:tenyear_guojia"] = "木美人",
	["tenyearyiji"] = "遗计",
	[":tenyearyiji"] = "当你受到1点伤害后，你可以摸两张牌，然后你可以将至多两张手牌交给一至两名其他角色。",
	
	["tenyear_zhenji"] = "界甄姬",
	["illustrator:tenyear_zhenji"] = "Town",
	["tenyearluoshen"] = "洛神",
	[":tenyearluoshen"] = "准备阶段开始时，你可以进行判定，当黑色判定牌生效后，你获得之。若结果为黑色，你可以重复此流程。以此法获得的牌本回合不计入手牌上限。",
	
	["tenyear_zhangliao"] = "界张辽",
	["illustrator:tenyear_zhangliao"] = "张帅",
	["tenyeartuxi"] = "突袭",
	[":tenyeartuxi"] = "摸牌阶段，你可以少摸任意张牌并获得等量的其他角色的各一张手牌。",
	
	["tenyear_huatuo"] = "界华佗",
	["tenyearqingnang"] = "青囊",
	[":tenyearqingnang"] = "<font color=\"green\"><b>出牌阶段每名角色限一次，</b></font>你可以弃置一张手牌并令一名已受伤角色回复1点体力。若你弃置的牌不为红色，此技能在本阶段内无效。",
	
	["tenyear_lvbu"] = "界吕布",
	["illustrator:tenyear_lvbu"] = "张帅",
	["tenyearliyu"] = "利驭",
	[":tenyearliyu"] = "当你使用【杀】对一名其他角色造成伤害后，你可获得其区域里的一张牌。然后若获得的牌不是装备牌，其摸一张牌；若获得的牌是装备牌，视为你对由其指定的另一名其他"..
						"角色使用一张【决斗】。",
	["@tenyearliyu"] = "请选择 %src 使用【决斗】的目标",
	
	["tenyear_diaochan"] = "界貂蝉",
	["illustrator:tenyear_diaochan"] = "木美人",
	["tenyearbiyue"] = "闭月",
	[":tenyearbiyue"] = "结束阶段开始时，你可以摸一张牌。若你没有手牌，改为摸两张牌。",
	
	["tenyear_huaxiong"] = "界华雄",
	["illustrator:tenyear_huaxiong"] = "秋呆呆",
	["tenyearyaowu"] = "耀武",
	[":tenyearyaowu"] = "锁定技，当你受到【杀】造成的伤害时，若此【杀】为红色，伤害来源回复1点体力或摸一张牌；若此【杀】不为红色，你摸一张牌。",
	["tenyearyaowu:draw"] = "摸一张牌",
	["tenyearyaowu:recover"] = "回复1点体力",
	
	["tenyear_huangzhong"] = "界黄忠",
	["tenyearliegong"] = "烈弓",
	[":tenyearliegong"] = "你使用【杀】可以选择距离不大于此【杀】点数的角色为目标；当你使用【杀】指定一个目标后，你可以根据下列条件执行相应的效果：1.其手牌数不大于你的手牌数，"..
						"其不能使用【闪】响应此【杀】；2.其体力值不小于你的体力值，此【杀】对其造成伤害时，伤害+1。",
						
	["tenyear_weiyan"] = "界魏延",
	["illustrator:tenyear_weiyan"] = "SoniaTang",
	["tenyearkuanggu"] = "狂骨",
	[":tenyearkuanggu"] = "当你造成1点伤害后，若你与受到此伤害的角色的距离于其因此伤害而扣减体力前不大于1，你可以回复1点体力或摸一张牌。",
	["tenyearkuanggu:recover"] = "回复1点体力",
	["tenyearkuanggu:draw"] = "摸一张牌",
	["tenyearqimou"] = "奇谋",
	[":tenyearqimou"] = "限定技，出牌阶段，你可以失去任意点体力，然后直到回合结束，你计算与其他角色的距离-X，且你可以多使用X张【杀】（X为你失去的体力值）。",
	
	["tenyear_xiahouyuan"] = "界夏侯渊",
	["tenyearshensu"] = "神速",
	[":tenyearshensu"] = "你可以选择至多三项：1.跳过判定阶段和摸牌阶段；2.跳过出牌阶段并弃置一张装备牌；3.跳过弃牌阶段并将武将牌翻面。你每选择一项，视为你使用一张无距离限制的【杀】。",
	["@tenyearshensu3"] = "你可以跳过弃牌阶段并将武将牌翻面发动“神速”",
	["~tenyearshensu1"] = "选择【杀】的目标角色→点击确定",
	["~tenyearshensu2"] = "选择一张装备牌和【杀】的目标角色→点击确定",
	["~tenyearshensu3"] = "选择【杀】的目标角色→点击确定",
	
	["tenyear_caoren"] = "界曹仁",
	["illustrator:tenyear_caoren"] = "Ccat",
	["tenyearjushou"] = "据守",
	[":tenyearjushou"] = "结束阶段开始时，你可以将武将牌翻面，若如此做，你摸四张牌，然后选择一项：1.弃置一张不为装备牌的牌；2.使用手牌中的一张装备牌。",
	["@tenyearjushou"] = "请弃置一张非装备牌或使用一张装备牌",
	["#TenyearjushouShow"] = "%from 没有可以弃置的非装备牌和可以使用的装备牌",
	["tenyearjiewei"] = "解围",
	[":tenyearjiewei"] = "你可以将装备区里的牌当【无懈可击】使用；当你的武将牌从背面翻至正面时，你可以弃置一张牌，然后移动场上的一张牌。",
	["@tenyearjiewei"] = "你可以弃置一张牌，然后移动场上的一张牌",
	
	["tenyear_xiaoqiao"] = "界小乔",
	["tenyeartianxiang"] = "天香",
	[":tenyeartianxiang"] = "当你受到伤害时，你可以弃置一张红桃手牌，防止此次伤害并选择一名其他角色，你选择一项：令其受到1点伤害，然后摸X张牌（X为其已损失体力值且至多为5）；"..
						"令其失去1点体力，然后其获得你弃置的牌。",
	["@tenyeartianxiang"] = "你可以弃置一张<font color=\"red\">♥</font>手牌发动“天香”",
	["~tenyeartianxiang"] = "选择一张<font color=\"red\">♥</font>手牌和一名其他角色→点“确定”",
	["tenyeartianxiang:damage"] = "令其受到1点伤害，然后摸X张牌",
	["tenyeartianxiang:losehp"] = "令其失去1点体力，然后其获得你弃置的牌",
	
	["tenyear_pangde"] = "界庞德",
	["illustrator:tenyear_pangde"] = "LiuHeng",
	["tenyearjianchu"] = "鞬出",
	[":tenyearjianchu"] = "当你使用【杀】指定一个目标后，你可以弃置其一张牌，若弃置的牌：是装备牌，该角色不能使用【闪】；不是装备牌，该角色获得此【杀】。",
	
	["tenyear_masu"] = "界马谡",
	["illustrator:tenyear_masu"] = "匠人绘",
	["tenyearsanyao"] = "散谣",
	[":tenyearsanyao"] = "出牌阶段限一次，你可以弃置任意张牌，然后对体力值最多的等量名其他角色各造成1点伤害。",
	["tenyearzhiman"] = "制蛮",
	[":tenyearzhiman"] = "当你对其他角色造成伤害时，你可以防止此伤害，然后获得其区域内一张牌。",
	
	["tenyear_yujin"] = "界于禁",
	["illustrator:tenyear_yujin"] = "biou09",
	["tenyearzhenjun"] = "镇军",
	[":tenyearzhenjun"] = "准备阶段开始时，你可以弃置一名角色X张牌（X为其手牌数减体力值且至少为1），然后选择一项：1.你弃置等于其中非装备牌数量的牌；2.该角色摸等于其中非装备牌"..
						"数量的牌。",
	["@tenyearzhenjun-invoke"] = "你可以发动“镇军”",
	["tenyearzhenjun-discard"] = "请弃置 %src 张牌，否则其摸牌",
	
	["second_tenyear_yujin"] = "界于禁-第二版",
	["illustrator:second_tenyear_yujin"] = "biou09",
	["secondtenyearzhenjun"] = "镇军",
	[":secondtenyearzhenjun"] = "准备阶段和结束阶段开始时，你可以弃置一名角色X张牌（X为其手牌数减体力值且至少为1），若其中没有装备牌，你选择一项：1.你弃置一张牌；2.该角色摸等量的牌。",
	["@secondtenyearzhenjun-invoke"] = "你可以发动“镇军”",
	["@secondtenyearzhenjun-discard"] = "请弃置一张牌，否则 %src 摸%arg张牌",
	
	["tenyear_guohuai"] = "界郭淮",
	["illustrator:tenyear_guohuai"] = "心中一凛",
	["tenyearjingce"] = "精策",
	[":tenyearjingce"] = "结束阶段开始时，若你于此回合内使用过的牌数量大于等于你的体力值，你可以摸两张牌。",
	
	["second_tenyear_guohuai"] = "界郭淮-第二版",
	["illustrator:second_tenyear_guohuai"] = "心中一凛",
	["secondtenyearjingce"] = "精策",
	[":secondtenyearjingce"] = "结束阶段开始时，若你于此回合内使用过的牌数大于等于你的体力值，你可以执行一个额外的摸牌或出牌阶段。若这些牌的花色数大于等于你的体力值，改为依次执行两项。",
	["secondtenyearjingce:draw"] = "执行一个额外的摸牌阶段",
	["secondtenyearjingce:play"] = "执行一个额外的出牌阶段",
	
	["tenyear_liaohua"] = "界廖化",
	["illustrator:tenyear_liaohua"] = "青岛君桓",
	["tenyeardangxian"] = "当先",
	[":tenyeardangxian"] = "锁定技，回合开始时，你执行一个额外的出牌阶段，此阶段开始时你失去1点体力并从弃牌堆获得一张【杀】。",
	[":tenyeardangxian2"] = "锁定技，回合开始时，你执行一个额外的出牌阶段。此阶段开始时，你可以失去1点体力并从弃牌堆获得一张【杀】。",
	["#TenyeardangxianPlayPhase"] = "%from 的“%arg”被触发，将进行一个额外的出牌阶段",
	["tenyearfuli"] = "伏枥",
	[":tenyearfuli"] = "限定技，当你处于濒死状态时，你可以将体力回复至X点且手牌摸至X张（X为全场势力数），然后“当先”中失去体力的效果改为可选。若X大于等于3，你将武将牌翻面。",
	
	["tenyear_chengpu"] = "界程普",
	["illustrator:tenyear_chengpu"] = "zoo",
	["tenyearchunlao"] = "醇醪",
	[":tenyearchunlao"] = "结束阶段开始时，若你没有“醇”，你可以将任意张【杀】置于武将牌上，称为“醇”；当一名角色处于濒死状态时，你可以移去一张“醇”，视为该角色使用一张【酒】。"..
	"若移去的“醇”为火【杀】，你回复1点体力；若移去的“醇”为雷【杀】，你摸两张牌。",
	["@tenyearchunlao"] = "你可以将任意张【杀】置于武将牌上，称为“醇”",
	["~tenyearchunlao"] = "选择若干张【杀】→点“确定”",
	
	["second_tenyear_chengpu"] = "界程普-第二版",
	["&second_tenyear_chengpu"] = "界程普",
	["illustrator:second_tenyear_chengpu"] = "zoo",
	["secondtenyearlihuo"] = "疠火",
	[":secondtenyearlihuo"] = "你可以将一张普通【杀】当火【杀】使用。你以此法使用【杀】结算后，若此【杀】造成了伤害，你失去1点体力。你使用火【杀】可以额外选择一名目标。若你每回合使用的第一张牌是【杀】，此【杀】结算完后，你可将其置于你的武将牌上，称为“醇”。",
	["secondtenyearlihuo:put"] = "你是否将此【杀】置于武将牌上？",
	["secondtenyearchunlao"] = "醇醪",
	[":secondtenyearchunlao"] = "出牌阶段结束时，若你没有“醇”，你可以将任意张【杀】置于武将牌上，称为“醇”；当一名角色处于濒死状态时，你可以移去一张“醇”，视为该角色使用一张【酒】。"..
	"若移去的“醇”为火【杀】，你回复1点体力；若移去的“醇”为雷【杀】，你摸两张牌。",
	["@secondtenyearchunlao"] = "你可以将任意张【杀】置于武将牌上，称为“醇”",
	["~secondtenyearchunlao"] = "选择若干张【杀】→点“确定”",
	
	["tenyear_caozhang"] = "界曹彰",
	["illustrator:tenyear_caozhang"] = "凝聚永恒",
	["tenyearjiangchi"] = "将驰",
	[":tenyearjiangchi"] = "摸牌阶段结束时，你可以选择一项：1.摸一张牌，本回合不能使用或打出【杀】；2.弃置一张牌，本回合使用【杀】无距离限制且可以额外使用一张【杀】。",
	["@tenyearjiangchi"] = "你可以发动“将驰”：点“确定”摸一张牌；或者弃置一张牌；或者点“取消”",
	["~tenyearjiangchi"] = "点“确定”摸牌；或弃置一张牌；或点“取消”",
	
	["second_tenyear_caozhang"] = "界曹彰-第二版",
	["&second_tenyear_caozhang"] = "界曹彰",
	["illustrator:second_tenyear_caozhang"] = "凝聚永恒",
	["secondtenyearjiangchi"] = "将驰",
	[":secondtenyearjiangchi"] = "出牌阶段开始时，你可以选择一项：1.摸两张牌，此阶段不能使用或打出【杀】；2.摸一张牌；3.弃置一张牌，然后此阶段使用【杀】无距离限制且可以额外使用一张【杀】。",
	["secondtenyearjiangchi:two"] = "摸两张牌，此阶段不能使用或打出【杀】",
	["secondtenyearjiangchi:one"] = "摸一张牌",
	["secondtenyearjiangchi:discard"] = "弃置一张牌，然后此阶段使用【杀】无距离限制且可以额外使用一张【杀】",
	
	["tenyear_zhangyi"] = "界张嶷",
	["illustrator:tenyear_zhangyi"] = "兴游",
	["tenyearwurong"] = "怃戎",
	[":tenyearwurong"] = "出牌阶段限一次，你可以和一名其他角色同时展示一张手牌：若你展示的是【杀】且该角色不是【闪】，你对其造成1点伤害；若你展示的不是【杀】且该角色是【闪】，"..
						"你获得其一张牌。",
	["@tenyearwurong-show"] = "请展示一张手牌",
	
	["second_tenyear_zhangyi"] = "界张嶷-第二版",
	["&second_tenyear_zhangyi"] = "界张嶷",
	["illustrator:second_tenyear_zhangyi"] = "兴游",
	["secondtenyearshizhi"] = "矢志",
	[":secondtenyearshizhi"] = "锁定技，若你的体力值为1，你的【闪】视为【杀】；你使用此【杀】造成伤害后，回复1点体力。",
	
	["tenyear_quancong"] = "界全琮",
	["illustrator:tenyear_quancong"] = "YanBai",
	["tenyearyaoming"] = "邀名",
	[":tenyearyaoming"] = "<font color=\"green\"><b>每回合每个选项限一次，</b></font>当你造成或受到伤害后，你可以选择一项：1.弃置手牌数大于你的一名角色的一张手牌；"..
						"2.令手牌数小于你的一名角色摸一张牌；3.令手牌数与你相同的角色弃置至多两张牌然后摸等量的牌。",
	["@tenyearyaoming-invoke"] = "你可以发动“邀名”",
	["tenyearyaoming-discard"] = "你可以弃置至多两张牌，然后摸等量的牌",
	
	["tenyear_zhuran"] = "界朱然",
	["illustrator:tenyear_zhuran"] = "F.源",
	["tenyeardanshou"] = "胆守",
	[":tenyeardanshou"] = "<font color=\"green\"><b>每回合限一次，</b></font>当你成为基本牌或锦囊牌的目标后，你可以摸X张牌（X为你本回合成为牌的目标次数）；"..
			"当前回合角色的结束阶段，若你本回合没有以此法摸牌，你可以弃置与其手牌数相同的牌数对其造成1点伤害。",
	["tenyeardanshou:tenyeardanshou_invoke"] = "你要发动“胆守”摸 %src 张牌吗？",
	["@tenyeardanshou-dis"] = "你可以弃置 %arg 张牌对 %src 造成1点伤害",
	["tenyeardanshou:tenyeardanshou_damage"] = "你是否发动“胆守”对 %src 造成1点伤害？",
	
	["tenyear_sunluban"] = "界孙鲁班",
	["illustrator:tenyear_sunluban"] = "匠人绘",
	["tenyearzenhui"] = "谮毁",
	[":tenyearzenhui"] = "当你使用【杀】或非延时类锦囊牌指定唯一目标时，你可令另一名其他角色选择一项：1.交给你一张牌，然后代替你成为此牌的使用者；"..
						"2.也成为此牌的目标（然后此技能本回合失效）。",
	["@tenyearzenhui-invoke"] = "你可以发动“谮毁”",
	["@tenyearzenhui-collateral"] = "请选择【借刀杀人】 %src 使用【杀】的目标",
	["tenyearzenhui-give"] = "请交给 %src 一张牌，否则你也成为目标",
	["tenyearzenhui-mustgive"] = "请交给 %src 一张牌",
	["tenyearjiaojin"] = "骄矜",
	[":tenyearjiaojin"] = "当你成为其他角色使用【杀】或非延时类锦囊牌的目标后，你可以弃置一张装备牌，然后此牌对你无效并获得此牌（若使用者为女性角色，此技能本回合失效）。",
	["@tenyearjiaojin"] = "%src对你使用了【%arg】，你可以发动“骄矜”弃置一张装备牌",
	
	["tenyear_wuyi"] = "界吴懿",
	["illustrator:tenyear_wuyi"] = "青岛磐蒲",
	["tenyearbenxi"] = "奔袭",
	[":tenyearbenxi"] = "锁定技，当你于回合内使用牌时，本回合你与其他角色的距离-1；你的回合内，若你与所有其他角色的距离均为1，你使用仅指定一个目标的【杀】或非延时类锦囊牌时"..
					"依次选择至多两项：1.此牌目标+1；2.此牌无视防具；3.此牌不能被抵消；4.此牌造成伤害时，你摸一张牌。",
	["tenyearbenxi:extra"] = "此牌目标+1",
	["tenyearbenxi:ignore"] = "此牌无视防具",
	["tenyearbenxi:noresponse"] = "此牌不能被抵消",
	["tenyearbenxi:draw"] = "此牌造成伤害时，你摸一张牌。",
	["@tenyearbenxi-extra"] = "请选择【%src】的额外目标",
	["~tenyearbenxi"] = "选择【借刀杀人】和【杀】的额外目标→点“确定”",
	
	["tenyear_xuhuang"] = "界徐晃",
	["illustrator:tenyear_xuhuang"] = "波子",
	["tenyearduanliang"] = "断粮",
	[":tenyearduanliang"] = "你可以将一张黑色基本牌或装备牌当【兵粮寸断】使用；你对手牌数大于等于你的角色使用【兵粮寸断】无距离限制。",
	["tenyearjiezi"] = "截辎",
	[":tenyearjiezi"] = "锁定技，一名其他角色跳过摸牌阶段后，你摸一张牌。",
	
	["tenyear_panfeng"] = "界潘凤",
	["illustrator:tenyear_panfeng"] = "游江",
	["tenyearkuangfu"] = "狂斧",
	[":tenyearkuangfu"] = "出牌阶段限一次，你可以弃置场上一张装备牌，然后视为使用一张【杀】（不计次数，无视距离）。若弃置的不是你的牌且【杀】没有造成伤害，你弃置两张手牌；"..
						"若弃置的是你的牌且【杀】造成了伤害，你摸两张牌。",
	["@tenyearkuangfu"] = "请选择【杀】的目标",
	["~tenyearkuangfu"] = "选择【杀】的目标→点“确定”",
	
	["tenyear_xusheng"] = "界徐盛",
	["illustrator:tenyear_xusheng"] = "黑羽",
	["tenyearpojun"] = "破军",
	[":tenyearpojun"] = "你使用【杀】指定目标后，你可以将其至多X张牌（X为其体力值）背面向上移出游戏直到回合结束：若其中有装备牌，弃置其中一张；若其中有锦囊牌，你摸一张牌。",
	["tenyearpojun_num"] = "请选择“破军”移除的牌数",
	["tenyearpojun_dis"] = "请选择“破军”移除的牌",
	
	["tenyear_sunhao"] = "界孙皓",
	["illustrator:tenyear_sunhao"] = "Liuheng",
	["tenyearcanshi"] = "残蚀",
	[":tenyearcanshi"] = "摸牌阶段，你可以额外摸X张牌（X为已受伤的角色数），然后本回合你使用【杀】或非延时类锦囊牌时，弃置一张牌。",
	["@tenyearcanshi-discard"] = "请弃置一张牌",
	["tenyearchouhai"] = "仇海",
	[":tenyearchouhai"] = "锁定技，当你受到【杀】的伤害时，若你没有手牌，此伤害+1。",
	
	["tenyear_sunxiu"] = "界孙休",
	["illustrator:tenyear_sunxiu"] = "写之火工作室",
	["tenyearyanzhu"] = "宴诛",
	[":tenyearyanzhu"] = "出牌阶段限一次，你可以令一名其他角色选择一项：1.令你获得其装备区里的所有牌，你修改“宴诛”和“兴学”；2.弃置一张牌且下一次受到的伤害+1直到其下回合开始。",
	[":tenyearyanzhu2"] = "出牌阶段限一次，你可以令一名其他角色下一次受到的伤害+1直到其下个回合开始。",
	["@tenyearyanzhu-discard"] = "请弃置一张牌且下一次受到的伤害+1，否则 %src 获得你装备区里所有牌",
	["@tenyearyanzhu-discard2"] = "请弃置一张牌，且下一次受到的伤害+1",
	["#TenyearyanzhuDamage"] = "%from 的“%arg”效果被触发，伤害增加 %arg2 点",
	["tenyearxingxue"] = "兴学",
	[":tenyearxingxue"] = "结束阶段开始时，你可以令至多X名角色（X为你的体力值）依次摸一张牌，然后其中手牌数大于体力值的角色依次将一张牌置于牌堆顶。",
	[":tenyearxingxue2"] = "结束阶段开始时，你可以令至多X名角色（X为你的体力上限）依次摸一张牌，然后其中手牌数大于体力值的角色依次将一张牌置于牌堆顶。",
	["@tenyearxingxue"] = "你可以选择至多 %src 名角色，发动“兴学”",
	["~tenyearxingxue"] = "选择若干名目标角色→点“确定”",
	["@tenyearxingxue-put"] = "请将一张牌置于牌堆顶",
	
	["tenyear_caoxiu"] = "界曹休",
	["illustrator:tenyear_caoxiu"] = "写之火工作室",
	["tenyearqingxi"] = "倾袭",
	[":tenyearqingxi"] = "当你使用【杀】或【决斗】指定目标后，你可令其选择一项：1.弃置等同于你攻击范围内的人数张手牌（最多为二，若你武器区有武器牌，则改为最多为四），然后弃置你的武器牌；2.令此牌对其伤害+1且进行一次判定，若结果为红色，此牌不能被该角色响应。",
	["@tenyearqingxi-discard"] = "请弃置 %src 张手牌，否则伤害+1",
	
	["tenyear_panzhangmazhong"] = "界潘璋＆马忠",
	["&tenyear_panzhangmazhong"] = "界潘璋马忠",
	["illustrator:tenyear_panzhangmazhong"] = "青学",
	["tenyearduodao"] = "夺刀",
	[":tenyearduodao"] = "当你成为【杀】的目标后，你可以弃置一张牌，然后获得使用者装备区里的武器牌。",
	["@tenyearduodao"] = "你可以弃置一张牌，获得 %src 装备区内的武器牌",
	["tenyearanjian"] = "暗箭",
	[":tenyearanjian"] = "锁定技，当你使用【杀】指定目标后，若你不在其攻击范围内，此【杀】无视防具且伤害+1，若该角色因此进入濒死状态，其不能使用【桃】，直至其濒死结算完。",
	
	["tenyear_hanhaoshihuan"] = "界韩浩＆史涣",
	["&tenyear_hanhaoshihuan"] = "界韩浩史涣",
	["illustrator:tenyear_hanhaoshihuan"] = "alien",
	["tenyearshenduan"] = "慎断",
	[":tenyearshenduan"] = "当你的一张黑色基本牌或黑色装备牌因弃置而置入弃牌堆后，你可以将此牌当【兵粮寸断】使用（无距离限制）。",
	["@tenyearshenduan"] = "你可以将一张牌当【兵粮寸断】使用（无距离限制）",
	["~tenyearshenduan"] = "选择一张牌→点“确定”",
	["#tenyearshenduan"] = "慎断",
	["tenyearyonglve"] = "勇略",
	[":tenyearyonglve"] = "一名其他角色的判定阶段开始时，你可以弃置其判定区里的一张牌。然后若该角色：在你攻击范围内，你摸一张牌；在你攻击范围外，视为你对其使用一张【杀】。",
	["tenyearyonglve:tenyearyonglve_in"] = "你是否对 %src 发动“勇略”？（在你的攻击范围内）",
	["tenyearyonglve:tenyearyonglve_out"] = "你是否对 %src 发动“勇略”？（在你的攻击范围外）",
	
	["tenyear_jianyong"] = "界简雍",
	["illustrator:tenyear_jianyong"] = "黑羽",
	["tenyearqiaoshui"] = "巧说",
	[":tenyearqiaoshui"] = "出牌阶段，你可以与一名角色拼点：若你赢，本回合你使用的下一张基本牌或非延时类锦囊牌可以多选或少选一个目标（无距离限制）；若你没赢，你结束出牌阶段且本回合锦囊牌不计入手牌上限。",
	["@tenyearqiaoshui1"] = "你可以为 【%src】 选择额外目标",
	["~tenyearqiaoshui1"] = "选择此牌的额外目标→点“确定”",
	["@tenyearqiaoshui2"] = "你可以为 【%src】 移除目标",
	["~tenyearqiaoshui2"] = "选择此牌移除的目标→点“确定”",
	["tenyearqiaoshui:add"] = "增加目标",
	["tenyearqiaoshui:remove"] = "减少目标",
	
	["tenyear_zhugeke"] = "界诸葛恪",
	["illustrator:tenyear_zhugeke"] = "LiuHeng",
	["tenyearaocai"] = "傲才",
	[":tenyearaocai"] = "你的回合外，每当你需要使用或打出一张基本牌时，你可以观看牌堆顶的两张牌（若你没有手牌，改为四张），然后使用或打出其中一张该类别的基本牌。",
	["tenyearduwu"] = "黩武",
	[":tenyearduwu"] = "出牌阶段，你可以弃置任意数量的牌并选择攻击范围内的一名体力值等于该数量的角色：若如此做，你对该角色造成1点伤害。若此伤害令该角色进入濒死状态，濒死结算后若其存活，你失去1点体力，且本回合“黩武”无效。",

	["tenyear_yangxiu"] = "界杨修",
	["illustrator:tenyear_yangxiu"] = "张可",
	["tenyeardanlao"] = "啖酪",
	[":tenyeardanlao"] = "当你成为【杀】或锦囊牌的目标后，若你不是此牌的唯一目标，你可以摸一张牌，然后此牌对你无效。",
	["tenyearjilei"] = "鸡肋",
	[":tenyearjilei"] = "当你受到伤害后，你可以声明一种牌的类别，伤害来源不能使用、打出或弃置你声明的此类手牌直到其下回合开始。",
	
	["tenyear_gaoshun"] = "界高顺",
	["illustrator:tenyear_gaoshun"] = "兴游",
	["tenyearxianzhen"] = "陷阵",
	[":tenyearxianzhen"] = "出牌阶段限一次，你可以与一名角色拼点：若你赢，本回合你无视该角色的防具、对其使用牌没有距离和次数限制，且你使用非延时类锦囊牌（【借刀杀人】除外）或【杀】仅指定单一目标后，可额外指定该角色为目标；若你没赢，本回合你不能使用【杀】且你的【杀】不计入手牌上限。",
	["@tenyearxianzhen-target"] = "你可以为 【%src】 选择额外目标",
	
	["tenyear_shixie"] = "界士燮",
	["#tenyear_shixie"] = "雄长百越" ,
	["illustrator:tenyear_shixie"] = "铭zmy",
	["tenyearbiluan"] = "避乱",
	[":tenyearbiluan"] = "结束阶段开始时，若有角色与你的距离为1，你可以弃置一张牌，令其他角色与你的距离+X（X为存活角色数且最多为4）。",
	["@tenyearbiluan-discard"] = "你可以弃置一张牌发动“避乱”",
	["tenyearlixia"] = "礼下" ,
	[":tenyearlixia"] = "锁定技，其他角色的结束阶段开始时，若你不在其攻击范围内，你选择一项：1.摸一张牌；2.令其摸两张牌。选择完成后，其他角色计算与你的距离-1。" ,
	["tenyearlixia:self"] = "摸一张牌",
	["tenyearlixia:other"] = "令其摸两张牌",
	
	["tenyear_liubiao"] = "界刘表",
	["illustrator:tenyear_liubiao"] = "聚一",
	["tenyearzishou"] = "自守",
	[":tenyearzishou"] = "摸牌阶段，你可以多摸X张牌（X为现存势力数），然后本回合你对其他角色造成伤害时，防止此伤害。结束阶段开始时，若你本回合没有使用牌指定其他角色为目标，你可以弃置任意张花色不同的手牌，然后摸等量的牌。",
	["tenyearzishou:tenyearzishou"] = "你是否发动“自守”多摸%src张牌？",
	["@tenyearzishou"] = "你可以弃置任意张花色不同的手牌，然后摸等量的牌",
	["~tenyearzishou"] = "选择若干张手牌→点“确定”",
	["tenyearzongshi"] = "宗室",
	[":tenyearzongshi"] = "锁定技，你的手牌上限+X（X为现存势力数）。你的回合外，若你的手牌数大于等于手牌上限，延时类锦囊牌或无颜色的牌对你无效。",
	["#TenyearzongshiAvoid"] = "%from 的“%arg”被触发，%card 对其无效",

	["tenyear_lingtong"] = "界凌统",
	["illustrator:tenyear_lingtong"] = "聚一",
	["tenyearxuanfeng"] = "旋风",
	[":tenyearxuanfeng"] = "当你于弃牌阶段弃置过至少两张牌，或当你失去装备区里的牌后，你可以弃置至多两名其他角色的共计两张牌。然后若此时是你的回合内，你可以对其中一名角色造成1点伤害。",
	["@tenyearxuanfeng-invoke"] = "你可以对其中一名角色造成1点伤害",
	["tenyearxuanfeng_damage"] = "旋风",
	["tenyearyongjin"] = "勇进",
	[":tenyearyongjin"] = "限定技，出牌阶段，你可以移动场上的至多三张装备牌。",

	["tenyear_fazheng"] = "界法正",
	["illustrator:tenyear_fazheng"] = "君桓文化",
	["tenyearenyuan"] = "恩怨",
	[":tenyearenyuan"] = "当你获得一名其他角色至少两张牌后，你可以令其摸一张牌；当你受到其他角色造成的1点伤害后，你可以令其选择一项：交给你一张手牌，若此牌不是红桃牌，你摸一张牌；或失去1点体力。",
	["tenyearxuanhuo"] = "眩惑",
	[":tenyearxuanhuo"] = "摸牌阶段结束时，若存活角色数大于2，你可以交给一名其他角色两张手牌，然后该角色选择一项：视为对你选择的另一名其他角色使用任意一种【杀】或【决斗】；或交给你所有手牌。",
	["@tenyearxuanhuo"] = "你可以交给一名其他角色两张手牌",
	["tenyearxuanhuo:use"] = "视为使用牌",
	["tenyearxuanhuo:give"] = "交出所有手牌",
	["@tenyearxuanhuo-target"] = "请选择 %src 使用牌的目标",
	["#TenyearxuanhuoTarget"] = "%from 选择了“%arg”使用牌的目标 %to",

	["tenyear_fuhuanghou"] = "界伏皇后",
	["illustrator:tenyear_fuhuanghou"] = "凝聚永恒",
	["tenyearzhuikong"] = "惴恐",
	[":tenyearzhuikong"] = "其他角色的回合开始时，若你已受伤，你可与其拼点，若你：赢，本回合该角色只能对自己使用牌；没赢，你获得其拼点的牌，然后其视为对你使用一张【杀】。",
	["tenyearqiuyuan"] = "求援",
	[":tenyearqiuyuan"] = "当你成为【杀】的目标时，你可以令另一名其他角色选择一项：交给你一张除【杀】以外的基本牌；或成为此【杀】的目标且不能响应此【杀】。",
	["@tenyearqiuyuan-invoke"] = "你可以发动“求援”",
	["@tenyearqiuyuan-give"] = "请交给 %src 一张除【杀】以外的基本牌，否则你也成为此【杀】的目标",
	
	["tenyear_caozhen"] = "界曹真",
	["illustrator:tenyear_caozhen"] = "凝聚永恒",
	["tenyearsidi"] = "司敌",
	[":tenyearsidi"] = "结束阶段开始时，你可以将一张非基本牌置于武将牌上，称为“司敌”。其他角色的出牌阶段开始时，你可以移去一张“司敌”牌，然后该角色于此阶段内不能使用或打出与此“司敌”牌颜色相同的牌。此阶段结束时，若其没有使用【杀】，视为对其使用一张【杀】；若其没有使用锦囊牌，你摸两张牌。",
	["@tenyearsidi-put"] = "你可以将一张非基本牌置于武将牌上，称为“司敌”",
	["@tenyearsidi"] = "你可以移去一张“司敌”牌，令 %src 不能使用或打出相同颜色的牌",
	
	["tenyear_gongsunyuan"] = "界公孙渊",
	["illustrator:tenyear_gongsunyuan"] = "君桓文化",
	["tenyearhuaiyi"] = "怀异",
	[":tenyearhuaiyi"] = "出牌阶段限一次，你可以展示所有手牌。若只有一种颜色，你摸一张牌，然后此技能本阶段改为“出牌阶段限两次”；若有两种颜色，你弃置其中一种颜色的牌，然后获得至多X名角色的各一张牌（X为弃置的手牌数）。若你获得的牌大于一张，你失去1点体力",
	["tenyearhuaiyi:red"] = "弃置红色牌",
	["tenyearhuaiyi:black"] = "弃置黑色牌",
	["@tenyearhuaiyi"] = "请获得至多 %src 名角色的各一张牌",
	
	["tenyear_zhangchunhua"] = "界张春华",
	["illustrator:tenyear_zhangchunhua"] = "磐浦",
	["tenyearjueqing"] = "绝情",
	[":tenyearjueqing"] = "当你造成伤害时，你可以失去等量的体力令此伤害值翻倍。然后，此伤害结算完后，此技能改为：“锁定技，你即将造成的伤害视为失去体力。”",
	[":tenyearjueqing2"] = "锁定技，你即将造成的伤害视为失去体力。",

	["tenyear_handang"] = "界韩当",
	["illustrator:tenyear_handang"] = "君桓文化",
	["tenyeargongqi"] = "弓骑",
	[":tenyeargongqi"] = "出牌阶段限一次，你可以弃置一张牌使你本回合的攻击范围无限，且与弃置的牌花色相同的【杀】无次数限制。若弃置的为装备牌，你可以弃置一名其他角色的一张牌。",
	["tenyearjiefan"] = "解烦",
	[":tenyearjiefan"] = "限定技，出牌阶段，你可以选择一名角色，令攻击范围内包含该角色的角色各选择一项：1.弃置一张武器牌；2.令该角色摸一张牌。若此时是第一轮游戏，则回合结束时此限定技视为未发动过。",

	["tenyear_zhoucang"] = "界周仓",
	["illustrator:tenyear_zhoucang"] = "君桓文化",
	["tenyearzhongyong"] = "忠勇",
	[":tenyearzhongyong"] = "当你使用的【杀】结算完后，你可以将此【杀】及目标角色使用的【闪】交给一名其他角色。若其中有红色牌，其可对你攻击范围内的角色使用一张【杀】；若其中有黑色牌，其摸一张牌。",
	["@tenyearzhongyong-invoke"] = "你可以将这些牌交给一名角色",
	
	["tenyear_guotupangji"] = "界郭图＆逢纪",
	["&tenyear_guotupangji"] = "界郭图逢纪",
	["#tenyear_guotupangji"] = "凶蛇两端",
	["illustrator:tenyear_guotupangji"] = "磐蒲",
	["tenyearjigong"] = "急攻",
	[":tenyearjigong"] = "出牌阶段开始时，你可以摸至多三张牌，然后你本回合的手牌上限等于X（X为你此阶段造成的伤害值）。然后此回合的弃牌阶段开始时，若X大于等于你以此法摸的牌数，你回复1点体力。",
	["tenyearjigong:1"] = "摸一张牌",
	["tenyearjigong:2"] = "摸两张牌",
	["tenyearjigong:3"] = "摸三张牌",
	
	["tenyear_guanping"] = "界关平",
	["illustrator:tenyear_guanping"] = "君桓文化",
	["tenyearjiezhong"] = "竭忠",
	[":tenyearjiezhong"] = "限定技，出牌阶段开始时，你可以将手牌摸至体力上限。",
	["tenyearlongyin"] = "龙吟",
	[":tenyearlongyin"] = "当一名角色于其出牌阶段内使用【杀】时，你可以弃置一张牌，令此【杀】不计入出牌阶段的使用次数，然后若此【杀】为红色，你摸一张牌。若你弃置的牌与【杀】点数相同，“竭忠”视为未发动过。",
	["@tenyearlongyin"] = "你可以弃置一张牌令 %src 使用的【杀】不计次",
	["#TenyearLongyinReset"] = "%from 的“%arg”被触发，“%arg2”视为未发动",
	
	["tenyear_caifuren"] = "界蔡夫人",
	["illustrator:tenyear_caifuren"] = "合子映画",
	["tenyearqieting"] = "窃听",
	[":tenyearqieting"] = "其他角色的回合结束时，若其本回合没有造成过伤害，你可以将其装备区里的一张牌置入你的装备区；若其没有对其他角色使用过牌，你摸一张牌。",
	["tenyearqieting:move"] = "你是否发动“窃听”移动%src装备区里的牌？",
	["tenyearxianzhou"] = "献州",
	[":tenyearxianzhou"] = "限定技，出牌阶段，你可以将装备区里的所有牌交给一名其他角色，然后你回复X点体力，且对其攻击范围内至多X名角色各造成1点伤害（X为你交给该角色牌的数量）。",
	["@tenyearxianzhou"] = "请对 %src 攻击范围内至多 %arg 名角色造成1点伤害",
	
	["tenyear_guyong"] = "界顾雍",
	["illustrator:tenyear_guyong"] = "福州明暗",
	["tenyearshenxing"] = "慎行",
	[":tenyearshenxing"] = "出牌阶段，你可以弃置X张牌，然后摸一张牌（X为你本阶段已发动此技能的次数且最多为2）。",
	["tenyearbingyi"] = "秉壹",
	[":tenyearbingyi"] = "结束阶段开始时，你可以展示所有手牌，若颜色均相同，你令至多X名角色各摸一张牌（X为你的手牌数）；若点数均相同，你摸一张牌。",
	["@tenyearbingyi"] = "你可以展示所有手牌发动“秉壹”",
	["~tenyearbingyi"] = "若手牌均为同一颜色，选择至多X名角色→点击“确定”；否则直接点击“确定”",
	
	["tenyear_wangyi"] = "界王异",
	["illustrator:tenyear_wangyi"] = "夏季与杨杨",
	
	["tenyear_yufan"] = "界虞翻",
	["illustrator:tenyear_yufan"] = "君桓文化",
	["tenyearzongxuan"] = "纵玄",
	[":tenyearzongxuan"] = "当你的牌因弃置而置入弃牌堆后，若其中：有锦囊牌，你可令一名其他角色获得其中一张锦囊牌，然后你将其余的牌中至少一张牌置于牌堆顶；没有锦囊牌，你可以将其中至少一张牌置于牌堆顶。",
	["@tenyearzongxuan-trick"] = "你可令一名其他角色获得其中一张锦囊牌",
	["@tenyearzongxuan"] = "请将至少一张牌置于牌堆顶",
	["#tenyearzongxuan"] = "纵玄",
	["tenyearzhiyan"] = "直言",
	[":tenyearzhiyan"] = "结束阶段开始时，你可以令一名角色摸一张牌并展示之，若此牌为：基本牌，你摸一张牌；装备牌，其使用之并回复1点体力。",
	
	["tenyear_xiahoushi"] = "界夏侯氏",
	["illustrator:tenyear_xiahoushi"] = "匠人绘",
	["tenyearqiaoshi"] = "樵拾",
	[":tenyearqiaoshi"] = "其他角色的结束阶段开始时，若其手牌数与你相同，你可以与其各摸一张牌，若这两张牌花色相同，你可以重复此流程。",
	["tenyearyjyanyu"] = "燕语",
	[":tenyearyjyanyu"] = "出牌阶段，你可以重铸【杀】。出牌阶段结束时，你可令一名男性角色摸X牌（X为你此阶段以此法重铸【杀】的数量且至多为3）。",
	["@tenyearyjyanyu-give"] = "你可以令一名男性角色摸%src张牌。",
	
	["tenyear_madai"] = "界马岱",
	["illustrator:tenyear_madai"] = "君桓文化",
	["tenyearqianxi"] = "潜袭",
	[":tenyearqianxi"] = "准备阶段开始时，你可以摸一张牌并弃置一张牌，然后令一名你与其距离为1的角色于此回合内：不能使用或打出与你弃置的牌颜色相同的手牌；与你弃置的牌颜色相同的防具无效；回复体力后，你摸两张牌。",

	["tenyear_guohuanghou"] = "界郭皇后",
	["illustrator:tenyear_guohuanghou"] = "匠人绘",
	["tenyearjiaozhao"] = "矫诏",
	[":tenyearjiaozhao"] = "出牌阶段限一次，你可以展示一张手牌，然后令一名你距离最近的角色声明一种基本牌或非延时类锦囊牌，本回合你可将此牌当声明的牌使用（不能对自己使用）。",
	[":tenyearjiaozhao1"] = "出牌阶段限一次，你可以展示一张手牌并声明一种基本牌或非延时类锦囊牌，本回合你可将此牌当声明的牌使用（不能对自己使用）。",
	[":tenyearjiaozhao2"] = "出牌阶段，你可以展示一张手牌并声明一种基本牌或非延时类锦囊牌，本回合你可将此牌当声明的牌使用（每种类型的牌限一次）。",
	["tenyearjiaozhao:show"] = "展示一张手牌",
	["tenyearjiaozhao:use"] = "将牌当【%src】使用",
	["tenyearjiaozhao:basic"] = "将牌当【%src】使用",
	["tenyearjiaozhao:trick"] = "将牌当【%src】使用",
	["tenyearjiaozhao_level"] = "矫诏升级",
	["tenyeardanxin"] = "殚心",
	[":tenyeardanxin"] = "当你受到伤害后，你可以摸一张牌，然后修改“矫诏”。",
	
	["tenyear_wuguotai"] = "界吴国太",
	["illustrator:tenyear_wuguotai"] = "匠人绘",
	["tenyearganlu"] = "甘露",
	[":tenyearganlu"] = "出牌阶段限一次，你可以交换两名角色装备区内的牌，然后若这两名角色装备区内牌数之差大于你已损失体力值，你弃置两张手牌。",
	["tenyearbuyi"] = "补益",
	[":tenyearbuyi"] = "当一名角色进入濒死状态时，你可以展示其一张手牌，若此牌不是基本牌，其弃置此牌，然后回复1点体力。当一名角色以此法弃置最后一张手牌后，其摸一张牌。",
}

