-- translation for Li Package

return {
	["li"] = "理包",
	
	["yinni_hide"] = "隐匿",
	
	["jin_simayi"] = "司马懿",
	["#jin_simayi"] = "通达权变",
	["illustrator:jin_simayi"] = "",
	["jinbuchen"] = "不臣",
	[":jinbuchen"] = "隐匿技，当你于其他角色的回合登场后，你可以获得当前回合角色的一张牌。",
	["jinyingshi"] = "鹰视",
	[":jinyingshi"] = "锁定技，出牌阶段，牌堆顶的X张牌对你可见（X为你的体力上限）。\n<font color=\"red\"><b>◆和OL一样，需要点一下技能图标</b></font>",
	["jinxiongzhi"] = "雄志",
	[":jinxiongzhi"] = "限定技，出牌阶段，你可以观看牌堆顶的一张牌，若你能使用此牌，你使用之，然后重复此流程。",
	["@jinxiongzhi"] = "请使用 【%src】",
	["#jinxiongzhi"] = "雄志",
	["jinquanbian"] = "权变",
	[":jinquanbian"] = "当你于出牌阶段内第一次使用或打出一种花色的手牌时，你可以从牌堆顶的X张牌中获得一张与此牌花色不同的牌，并将其余牌以任意顺序置于牌堆顶。出牌阶段，你至多可使用X张手牌（X为你的体力上限）。",
	
	["second_jin_simayi"] = "司马懿-第二版",
	["&second_jin_simayi"] = "司马懿",
	["#second_jin_simayi"] = "通达权变",
	["illustrator:second_jin_simayi"] = "",
	["secondjinquanbian"] = "权变",
	[":secondjinquanbian"] = "当你于出牌阶段内第一次使用或打出一种花色的手牌时，你可以从牌堆顶的X张牌中获得一张与此牌花色不同的牌，并将其余牌以任意顺序置于牌堆顶。出牌阶段，你至多可使用X张非装备手牌（X为你的体力上限）。",
	
	["jin_zhangchunhua"] = "张春华",
	["#jin_zhangchunhua"] = "宣穆皇后",
	["illustrator:jin_zhangchunhua"] = "凝聚永恒",
	["jinhuishi"] = "慧识",
	[":jinhuishi"] = "摸牌阶段，你可以改为观看牌堆顶的X张牌，获得其中一半的牌（向下取整），然后将其余的牌置于牌堆底（X为牌堆数量的个位数）。",
	["jinhuishi:jinhuishi_invoke"] = "你是否发动“慧识”，观看牌堆顶的 %src 张牌？",
	["jinqingleng"] = "清冷",
	[":jinqingleng"] = "一名角色的回合结束时，若其体力值与手牌数之和不小于X（X为牌堆数量的个位数），你可将一张牌当无距离限制的冰【杀】对其使用。你以此法使用牌时，你摸X张牌（X为目标角色中未成为过“清冷”的角色数）。",
	["@jinqingleng"] = "你可将一张牌当冰【杀】对 %src 使用",
	["jinxuanmu"] = "宣穆",
	[":jinxuanmu"] = "隐匿技，锁定技，当你于其他角色的回合登场后：当你于本回合受到伤害时，防止此伤害。",
	
	["ol_lisu"] = "OL李肃",
	["&ol_lisu"] = "李肃",
	["#ol_lisu"] = "巧言令色",
	["illustrator:ol_lisu"] = "",
	["qiaoyan"] = "巧言",
	[":qiaoyan"] = "锁定技，当其他角色于你的回合外对你造成伤害时，若你：没有“珠”，你防止此伤害，摸一张牌，然后将一张牌置于武将牌上，称为“珠”；有“珠”，其获得“珠”。",
	["qyzhu"] = "珠",
	["@qiaoyan-put"] = "请将一张牌当“珠”置于武将牌上",
	["xianzhu"] = "献珠",
	[":xianzhu"] = "锁定技，出牌阶段开始时，你令一名角色获得“珠”。若该角色不是你，其视为对你攻击范围内你指定的一名角色使用一张【杀】。",
	["xianzhu_target"] = "献珠",
	["@xianzhu-invoke"] = "请选择一名角色获得“珠”",
	["@xianzhu-target"] = "请选择 %src 使用【杀】的目标",
	
	["jin_simazhou"] = "司马伷",
	["#jin_simazhou"] = "琅琊武王",
	["illustrator:jin_simazhou"] = "",
	["jincaiwang"] = "才望",
	[":jincaiwang"] = "你使用或打出牌响应其他角色使用的牌，或其他角色使用或打出牌响应你使用的牌时，若牌颜色相同，你可弃置其一张牌。",
	["jincaiwang:jincaiwang_discard"] = "你是否发动“才望”弃置 %src 的一张牌？",
	["jincaiwang:jincaiwang_get"] = "你是否发动“才望”获得 %src 的一张牌？",
	["jinnaxiang"] = "纳降",
	[":jinnaxiang"] = "锁定技，其他角色对你造成伤害或受到你对其造成的伤害后，你对其发动“才望”的“弃置”修改为“获得”直到你的回合开始。",
	
	["second_jin_simazhou"] = "司马伷-第二版",
	["&second_jin_simazhou"] = "司马伷",
	["#second_jin_simazhou"] = "琅琊武王",
	["illustrator:second_jin_simazhou"] = "",
	["secondjincaiwang"] = "才望",
	[":secondjincaiwang"] = "你使用或打出牌响应其他角色使用的牌，或其他角色使用或打出牌响应你使用的牌时，若牌颜色相同，你可弃置其一张牌。你可以将最后一张手牌当【闪】使用或打出，将最后一张你装备区的牌当【无懈可击】使用，将最后一张你判定区的牌当【杀】使用或打出。",
	["secondjincaiwang:jincaiwang_discard"] = "你是否发动“才望”弃置 %src 的一张牌？",
	["secondjincaiwang:jincaiwang_get"] = "你是否发动“才望”获得 %src 的一张牌？",
	
	["cheliji"] = "彻里吉",
	["#cheliji"] = "高凉铁骨",
	["illustrator:cheliji"] = "",
	["chexuan"] = "车悬",
	[":chexuan"] = "出牌阶段，若你的装备区里没有宝物牌，你可弃置一张黑色牌，选择一张【舆】置入你的装备区；当你不因替换装备而失去装备区里的宝物牌后，你可进行一次判定，若判定结果为黑色，你将一张随机的【舆】置入你的装备区。",
	["qiangshou"] = "羌首",
	[":qiangshou"] = "锁定技，若你的装备区里有宝物牌，你与其他角色的距离-1。",
	
	["ol_huaxin"] = "OL华歆",
	["&ol_huaxin"] = "华歆",
	["illustrator:ol_huaxin"] = "",
	["caozhao"] = "草诏",
	[":caozhao"] = "出牌阶段限一次，你可展示一张手牌并声明一种未以此法声明过的基本牌或非延时类锦囊牌，令一名体力值不大于你的角色选择一项：你可将其交给一名其他角色，且此牌视为你声明的牌直到离开拥有者手牌；或失去1点体力。",
	["@caozhao-target"] = "请选择一名体力值不大于你的角色",
	["caozhao:view"] = "令【%src】视为【%arg】",
	["caozhao:losehp"] = "失去1点体力",
	["caozhao_give"] = "草诏",
	["@caozhao-give"] = "你可以将此牌交给一名其他角色",
	["olxibing"] = "息兵",
	[":olxibing"] = "每当你受到其他角色造成的伤害时，你可弃置你或该角色的两张牌，然后你们中手牌少的角色摸两张牌，且不能使用牌指定你为目标直到回合结束。",
	["olxibing:discard"] = "弃置%src两张牌",
	["olxibing:discard_self"] = "弃置自己两张牌",
}
