-- translation for MobileXin Package

return {
	["mobilexin"] = "手杀信包",

	["mobilexin_xinpi"] = "辛毗",
	["illustrator:mobilexin_xinpi"] = "",
	["mobilexinyinju"] = "引裾",
	[":mobilexinyinju"] = "出牌阶段限一次，你可令一名其他角色选择一项：在其下一个准备阶段开始时，跳过出牌阶段和弃牌阶段；或对你使用一张【杀】。",
	["@mobilexinyinju-slash"] = "请对 %src 使用一张【杀】，否则你将跳过出牌阶段和弃牌阶段",
	["mobilexinchijie"] = "持节",
	[":mobilexinchijie"] = "每个回合限一次，当你成为其他角色使用牌的唯一目标时，你可以进行一次判定。若判定结果点数大于6，取消之。",
	
	["second_mobilexin_xinpi"] = "辛毗-第二版",
	["&second_mobilexin_xinpi"] = "辛毗",
	["illustrator:second_mobilexin_xinpi"] = "",
	["secondmobilexinyinju"] = "引裾",
	[":secondmobilexinyinju"] = "出牌阶段限一次，你可令一名其他角色选择一项：在其下一个准备阶段开始时，跳过出牌阶段和弃牌阶段；或对你使用一张无距离限制的【杀】。",
	["@secondmobilexinyinju-slash"] = "请对 %src 使用一张【杀】，否则你将跳过出牌阶段和弃牌阶段",
	
	["mobilexin_wangling"] = "王凌",
	["#mobilexin_wangling"] = "风节格尚",
	["illustrator:mobilexin_wangling"] = "",
	["mobilexinmouli"] = "谋立",
	[":mobilexinmouli"] = "出牌阶段限一次，你可将一张手牌交给一名其他角色，该角色获得一枚“立”标记直到你下回合开始，且当其使用的第一张【杀】或【闪】结算完后，你摸三张牌。拥有“立”标记的角色拥有以下技能：你可以将一张黑色牌当【杀】使用；你可以将一张红色牌当【闪】使用。",
	["mobilexinmouli_effect"] = "谋立",
	[":mobilexinmouli_effect"] = "你可以将一张黑色牌当【杀】使用；你可以将一张红色牌当【闪】使用。",
	["mobilexinli"] = "立",
	["mobilexinzifu"] = "自缚",
	[":mobilexinzifu"] = "锁定技，当拥有你给出的“立”标记的其他角色死亡时，你减2点体力上限。",
	
	["second_mobilexin_wangling"] = "王凌-第二版",
	["&second_mobilexin_wangling"] = "王凌",
	["#second_mobilexin_wangling"] = "风节格尚",
	["illustrator:second_mobilexin_wangling"] = "",
	["secondmobilexinxingqi"] = "星启",
	[":secondmobilexinxingqi"] = "当你使用一张不为延时类锦囊牌的牌时，若你没有同名的“备”，你将此牌的牌名记录于“备”中。结束阶段开始时，你可以移除一个“备”，然后获得牌堆中一张同名牌。",
	["#SecondMobileXinXingqiRemove"] = "%from 将 %arg 从“备”中移除",
	["#SecondMobileXinXingqiLog"] = "%from 将 %arg 记录为“备”",
	["secondmobilexinzifu"] = "自缚",
	[":secondmobilexinzifu"] = "锁定技，出牌阶段结束时，若你本阶段未使用过牌，你本回合手牌上限-1且移除你所有的“备”。",
	["secondmobilexinmibei"] = "秘备",
	[":secondmobilexinmibei"] = "使命技，\
		<font color=\"red\"><b>成功：</b></font>当你使用的牌结算完时，若你记录了每种类型的“备”各至少两个，你获得牌堆中每种类型的牌各一张，然后获得“谋立”。\
		<font color=\"blue\"><b>失败：</b></font>弃牌阶段结束时，若你此时和本回合的准备阶段开始时均没有“备”，你减1点体力上限。",
	["secondmobilexinmouli"] = "谋立",
	[":secondmobilexinmouli"] = "出牌阶段限一次，你可以令一名其他角色移除一个你的“备”，然后其获得牌堆中一张同名牌。",
	
	["mobilexin_mifuren"] = "糜夫人",
	["illustrator:mobilexin_mifuren"] = "",
	["mobilexincunsi"] = "存嗣",
	[":mobilexincunsi"] = "出牌阶段限一次，若你的武将牌正面向上，你可以将武将牌翻面并选择一名角色，令其随机获得牌堆或弃牌堆中的一张【杀】且使用的下一张【杀】造成的伤害+1。",
	["#MobileXinCunsiDamage"] = "%from 的“<font color=\"yellow\"><b>存嗣</b></font>”效果被触发，伤害由 %arg 点增至 %arg2 点",
	["mobilexinguixiu"] = "闺秀",
	[":mobilexinguixiu"] = "锁定技，当你受到伤害后，若你的武将牌背面向上，你将武将牌翻面。当你的武将牌翻回正面后，你摸一张牌。",
	
	["second_mobilexin_mifuren"] = "糜夫人-第二版",
	["&second_mobilexin_mifuren"] = "糜夫人",
	["illustrator:second_mobilexin_mifuren"] = "",
	["secondmobilexinguixiu"] = "闺秀",
	[":secondmobilexinguixiu"] = "锁定技，结束阶段开始时，若你的体力值为：奇数，你摸一张牌；偶数，你回复1点体力。",
	["secondmobilexinqingyu"] = "清玉",
	[":secondmobilexinqingyu"] = "使命技，当你受到伤害时，你弃置两张牌，然后防止此伤害。\
									<font color=\"red\"><b>成功：</b></font>准备阶段开始时，若你满体力且没有手牌，你获得技能“悬存”。\
									<font color=\"blue\"><b>失败：</b></font>你进入濒死状态时，减1点体力上限。",
	["secondmobilexinxuancun"] = "悬存",
	[":secondmobilexinxuancun"] = "其他角色的回合结束后，若你的体力值大于手牌数，你可以令其摸X张牌（X为你的体力值与手牌数之差，且至多为2）。",
	
	["mobilexin_wangfuzhaolei"] = "王甫＆赵累",
	["&mobilexin_wangfuzhaolei"] = "王甫赵累",
	["#mobilexin_wangfuzhaolei"] = "忱忠不移",
	["illustrator:mobilexin_wangfuzhaolei"] = "",
	["mobilexinxunyi"] = "殉义",
	[":mobilexinxunyi"] = "游戏开始时，你可以令一名其他角色获得一枚“义”标记。当你受到1点伤害后，若伤害来源不是该角色，其弃置一张牌；当该角色受到1点伤害后，若伤害来源不是你，你弃置一张牌。" ..
						"当你对除其外的角色造成1点伤害后，其摸一张牌；当其对除你外的角色造成1点伤害后，你摸一张牌。当拥有“义”标记的其他角色死亡时，你可以将此标记移动给另一名其他角色。",
	["mobilexinyi"] = "义",
	["@mobilexinxunyi-invoke"] = "你可以令一名其他角色获得一枚“义”标记",
	["@mobilexinxunyi-transfer"] = "你可以将“义”标记移动给一名其他角色",
	["#MobileXinXunyiTransferMark"] = "%from 将 %arg2 枚 %arg 标记转移给 %to",
	
	["mobilexin_wujing"] = "吴景",
	["#mobilexin_wujing"] = "助吴征战",
	["illustrator:mobilexin_wujing"] = "",
	["mobilexinheji"] = "合击",
	[":mobilexinheji"] = "当一名角色使用的红色【杀】或【决斗】结算完后，若此牌的目标数为1，你可以对相同目标使用手牌中的一张【杀】或【决斗】（不计次且无距离限制），若此牌不为转化牌，你随机获得牌堆或弃牌堆中的一张红色牌。",
	["@mobilexinheji-use"] = "你可以对 %src 使用一张【杀】或【决斗】（需要选一个目标，但是无论选谁，都会以其为目标）",
	
	["mobilexin_zhouchu"] = "周处",
	["#mobilexin_zhouchu"] = "英情天逸",
	["illustrator:mobilexin_zhouchu"] = "",
	["mobilexinxianghai"] = "乡害",
	[":mobilexinxianghai"] = "锁定技，其他角色的手牌上限-1。你手牌中的装备牌视为【酒】。",
	["mobilexinchuhai"] = "除害",
	[":mobilexinchuhai"] = "出牌阶段限一次，你可以摸一张牌，然后与一名其他角色拼点。若你赢：你观看其手牌，然后从牌堆或弃牌堆中获得其手牌中拥有的牌类型各一张；当你于此阶段对其造成伤害后，你将牌堆或弃牌堆中一张你空置的装备栏对应类型的装备牌置入你的装备区。",
	["@mobilexinchuhai-invoke"] = "请选择拼点的角色",
	["$MobileXinChuhaiPutEquipFromDrawPile"] = "%from 将 %card 从牌堆置入装备区",
	["$MobileXinChuhaiPutEquipFromDiscardPile"] = "%from 将 %card 从弃牌堆置入装备区",
	
	["mobilexin_kongrong"] = "孔融",
	["illustrator:mobilexin_kongrong"] = "",
	["mobilexinmingshi"] = "名士",
	[":mobilexinmingshi"] = "锁定技，当你受到1点伤害后，伤害来源弃置一张牌。",
	["mobilexinlirang"] = "礼让",
	[":mobilexinlirang"] = "出牌阶段限一次，你可以弃置所有手牌，然后你可以将其中至多X张在弃牌堆中的牌交给一名其他角色，然后你摸一张牌（X为你的体力值）。",
	["@mobilexinlirang-give"] = "你可以将至多 %src 张牌交给一名其他角色",
	
	["mobilexin_yanghu"] = "羊祜",
	["#mobilexin_yanghu"] = "鹤德璋声",
	["illustrator:mobilexin_yanghu"] = "",
	["mobilexinmingfa"] = "明伐",
	[":mobilexinmingfa"] = "结束阶段开始时，你可以展示一张牌。若如此做，下个出牌阶段开始时，你可以用属于你的此牌与一名其他角色拼点。若你：赢，你获得其一张牌，然后从牌堆内随机" ..
							"获得一张点数比你的拼点牌牌面点数小1的牌；没赢，本回合你不能对其他角色使用牌。你的拼点牌点数+2。",
	["@mobilexinmingfa-show"] = "你可以发动“明伐”展示一张牌",
	["@mobilexinmingfa-pindian"] = "请选择拼点目标",
	["#MobileXinMingfaPindian"] = "%from 的“%arg”被触发，拼点牌点数+2（视为 %arg2）",
	["mobilexinrongbei"] = "戎备",
	[":mobilexinrongbei"] = "限定技，出牌阶段，你可以选择一名有空置装备栏的角色，令其每个空置的装备栏均从牌堆内随机获得并使用一张装备牌。",
}
	