-- translation for MobileJXTP Package

return {
	["MobileJXTP"] = "手杀界限突破",
	
	["mobile_zhangfei"] = "手杀界张飞",
	["&mobile_zhangfei"] = "界张飞",
	["illustrator:mobile_zhangfei"] = "SONGQIJIN",
	["mobileliyong"] = "厉勇",
	[":mobileliyong"] = "锁定技，当你于出牌阶段使用的【杀】被【闪】抵消后，你本阶段下一次使用的【杀】指定目标后，其本回合非锁定技无效，且此【杀】不可被响应且伤害值+1；此【杀】造成伤害后，若该角色未死亡，你失去1点体力。",
	["#MobileliyongSkillInvalidity"] = "%from 的“%arg”被触发，%to 的非锁定技无效",
	
	["mobile_xiahoudun"] = "手杀界夏侯惇",
	["&mobile_xiahoudun"] = "界夏侯惇",
	["illustrator:mobile_xiahoudun"] = "DH",
	["mobileqingjian"] = "清俭",
	[":mobileqingjian"] = "每个回合限一次，当你于摸牌阶段外获得牌后，你可以将任意张手牌扣置于武将牌上；本回合结束时，你将这些牌交给任意名其他角色，若你以此法交出的牌多于一张，你摸一张牌。",
	["@mobileqingjian-put"] = "你可以将任意张手牌扣置于武将牌上",
	["@mobileqingjian"] = "请将“清俭”牌交给其他角色",
	["~mobileqingjian"] = "选择若干张牌→选择一名其他角色→点“确定”",
	
	["mobile_zhoutai"] = "手杀界周泰",
	["&mobile_zhoutai"] = "界周泰",
	["illustrator:mobile_zhoutai"] = "Thinking",
	["mobilefenji"] = "奋激",
	[":mobilefenji"] = "一名角色的回合结束时，若其没有手牌，你可以令其摸两张牌，然后你失去1点体力。",
	
	["mobile_wolong"] = "手杀界卧龙诸葛亮",
	["&mobile_wolong"] = "界卧龙诸葛亮",
	["illustrator:mobile_wolong"] = "YanBai",
	
	["mobile_dianwei"] = "手杀界典韦",
	["&mobile_dianwei"] = "界典韦",
	["illustrator:mobile_dianwei"] = "凝聚永恒",
	["mobileqiangxi"] = "强袭",
	[":mobileqiangxi"] = "<font color=\"green\"><b>出牌阶段对每名角色限一次，</b></font>你可以失去1点体力或弃置一张武器牌，然后对攻击范围内的一名其他角色造成1点伤害。",
	
	["mobile_xunyu"] = "手杀界荀彧",
	["&mobile_xunyu"] = "界荀彧",
	["illustrator:mobile_xunyu"] = "青岛磬蒲",
	["mobilejieming"] = "节命",
	[":mobilejieming"] = "当你受到1点伤害后，你可以令一名角色摸两张牌，然后若其手牌数小于其体力上限，你摸一张牌。",
	["@mobilejieming-invoke"] = "你可以发动“节命”令一名角色摸两张牌",
	
	["mobile_pangtong"] = "手杀界庞统",
	["&mobile_pangtong"] = "界庞统",
	["illustrator:mobile_pangtong"] = "青岛磬蒲",
	["mobileniepan"] = "涅槃",
	[":mobileniepan"] = "限定技，出牌阶段或当你处于濒死状态时，你可以弃置你的区域里的所有牌，摸三张牌，体力回复至3点，并复原你的武将牌。",
	
	["mobile_yanliangwenchou"] = "手杀界颜良＆文丑",
    ["&mobile_yanliangwenchou"] = "界颜良文丑",
	["illustrator:mobile_yanliangwenchou"] = "凝聚永恒",
	["mobileshuangxiong"] = "双雄",
	[":mobileshuangxiong"] = "摸牌阶段，你可以改为展示牌堆顶的两张牌，获得其中一张牌，然后此回合你可以将一张与该牌不同颜色的手牌当【决斗】使用；当你因“双雄”受到伤害后，你可以获得此次【决斗】中其他角色打出的【杀】。",
	["mobileshuangxiong:mobileshuangxiong_invoke"] = "你是否发动“双雄”获得 %src 打出的【杀】？",
	
	["mobile_yuanshao"] = "手杀界袁绍",
	["&mobile_yuanshao"] = "界袁绍",
	["illustrator:mobile_yuanshao"] = "17号",
	["mobileluanji"] = "乱击",
	[":mobileluanji"] = "出牌阶段，你可以将两张手牌当【万箭齐发】使用（本回合每种花色限一次）；当其他角色因响应你使用的【万箭齐发】而打出【闪】时，其摸一张牌；若没有角色受到你使用的【万箭齐发】的伤害，你摸等于此牌目标数的牌。",
	
	["mobile_menghuo"] = "手杀界孟获",
	["&mobile_menghuo"] = "界孟获",
	["illustrator:mobile_menghuo"] = "凝聚永恒",
	["mobilezaiqi"] = "再起",
	[":mobilezaiqi"] = "弃牌阶段结束时，你可以令至多X名角色各选择一项（X为本回合内置入弃牌堆的红色牌数）：摸一张牌；或令你回复1点体力。",
	["@mobilezaiqi"] = "你可以对至多 %src 名角色发动“再起”",
	["~mobilezaiqi"] = "选择目标角色→点“确定”",
	["mobilezaiqi:draw"] = "摸一张牌",
	["mobilezaiqi:recover"] = "令其回复1点体力",
	
	["mobile_zhurong"] = "手杀界祝融",
	["&mobile_zhurong"] = "界祝融",
	["illustrator:mobile_zhurong"] = "alien",
	["mobilelieren"] = "烈刃",
	[":mobilelieren"] = "当你使用【杀】指定目标后，你可以与目标角色拼点，若你：赢，你获得其一张牌；没赢，你与其交换拼点的牌。",
	
	["mobile_caopi"] = "手杀界曹丕",
	["&mobile_caopi"] = "界曹丕",
	["illustrator:mobile_caopi"] = "YanBai",
	["mobilexingshang"] = "行殇",
	[":mobilexingshang"] = "其他角色死亡时，你可以选择一项：获得其所有牌；回复1点体力。",
	["mobilexingshang:get"] = "获得其所有牌",
	["mobilexingshang:recover"] = "回复1点体力",
	["mobilefangzhu"] = "放逐",
	[":mobilefangzhu"] = "当你受到伤害后，你可以令一名其他角色选择一项：摸X张牌并将武将牌翻面；弃置X张牌并失去1点体力（X为你已损失的体力值）。",
	["@mobilefangzhu-invoke"] = "你可以发动“放逐”",
	["mobilefangzhu-discard"] = "请弃置 %src 张牌，否则摸 %src 张牌并翻面",
	
	["mobile_sunjian"] = "手杀界孙坚",
	["&mobile_sunjian"] = "界孙坚",
	["illustrator:mobile_sunjian"] = "漫想族",
	["mobilepolu"] = "破虏",
	[":mobilepolu"] = "当你杀死一名角色或死亡时，你可以令任意名角色各摸X+1张牌（X为你本局游戏已发动本技能的次数）。",
	["@mobilepolu"] = "你可以令任意名角色摸 %src 张牌",
	["~mobilepolu"] = "选择目标角色→点“确定”",
	
	["mobile_dongzhuo"] = "手杀界董卓",
	["&mobile_dongzhuo"] = "界董卓",
	["illustrator:mobile_dongzhuo"] = "天龙",
	["mobilejiuchi"] = "酒池",
	[":mobilejiuchi"] = "你可以将一张黑桃手牌当【酒】使用。你使用的受【酒】影响的【杀】造成伤害后，本回合“崩坏”失效。",
	["#BenghuaiNullification"] = "%from 的“%arg”被触发，本回合技能“%arg2”失效",
	
	["mobile_dengai"] = "手杀界邓艾",
	["&mobile_dengai"] = "界邓艾",
	["illustrator:mobile_dengai"] = "凝聚永恒",
	["mobiletuntian"] = "屯田",
	[":mobiletuntian"] = "当你于回合外失去牌后，你可以进行判定，若判定结果：为红桃，你获得生效后的判定牌；不为红桃，你将生效后的判定牌置于你的武将牌上，称为“田”；你与其他角色的距离-X（X为“田”的数量）。",
	
	["mobile_jiangwei"] = "手杀界姜维",
	["&mobile_jiangwei"] = "界姜维",
	["illustrator:mobile_jiangwei"] = "石蝉",
	["mobiletiaoxin"] = "挑衅",
	[":mobiletiaoxin"] = "出牌阶段限一次，你可以选择一名其他角色，然后其选择一项：对你使用一张【杀】；或你弃置其一张牌。",
	["@mobiletiaoxin-slash"] = "%src 对你发动“挑衅”，请对其使用一张【杀】",
	["mobilezhiji"] = "志继",
	[":mobilezhiji"] = "觉醒技，准备阶段开始时，若你没有手牌，你选择一项：回复1点体力；或摸两张牌。然后你减1点体力上限，获得“观星”。",
	["mobilezhiji:recover"] = "回复1点体力",
	["mobilezhiji:draw"] = "摸两张牌",
	
	["mobile_sunce"] = "手杀界孙策",
	["&mobile_sunce"] = "界孙策",
	["illustrator:mobile_sunce"] = "凝聚永恒",
	["mobilehunzi"] = "魂姿",
	[":mobilehunzi"] = "觉醒技，准备阶段开始时，若你的体力值不大于2，你减1点体力上限，然后获得技能“英姿”和“英魂”。",
	
	["mobile_caiwenji"] = "手杀界蔡文姬",
	["&mobile_caiwenji"] = "界蔡文姬",
	["illustrator:mobile_caiwenji"] = "青学",
	["mobilebeige"] = "悲歌",
	[":mobilebeige"] = "当一名角色受到【杀】的伤害后，你可以弃置一张牌令其进行判定，若判定结果为：红桃，其回复等同此次伤害值的体力；方块，其摸三张牌；梅花，伤害来源弃置两张牌；黑桃，伤害来源将武将牌翻面。",
	["@mobilebeige"] = "你可以弃置一张牌对 %src 发动“悲歌”",
	
	["mobile_erzhang"] = "手杀界张昭＆张纮",
    ["&mobile_erzhang"] = "界张昭张纮",
	["illustrator:mobile_erzhang"] = "绘聚艺堂",
	["mobilezhijian"] = "直谏",
	[":mobilezhijian"] = "出牌阶段，你可以将手牌中的一张装备牌置于一名其他角色装备区里，然后摸一张牌；当你于出牌阶段使用装备牌时，你摸一张牌。",
	
	["mobile_liushan"] = "手杀界刘禅",
	["&mobile_liushan"] = "界刘禅",
	["illustrator:mobile_liushan"] = "绘聚艺堂",
	["mobilefangquan"] = "放权",
	[":mobilefangquan"] = "你可以跳过出牌阶段，若如此做，你本回合手牌上限等于你的体力上限，然后此回合结束时，你可以弃置一张手牌令一名其他角色获得一个额外的回合。",
	["@mobilefangquan-give"] = "你可以弃置一张手牌令一名其他角色进行一个额外的回合",
	["~mobilefangquan"] = "选择一张手牌→选择一名其他角色→点击确定",
	
	["mobile_xusheng"] = "手杀界徐盛",
	["&mobile_xusheng"] = "界徐盛",
	["illustrator:mobile_xusheng"] = "铁杵文化",
	["mobilepojun"] = "破军",
	[":mobilepojun"] = "当你使用【杀】指定一个目标后，你可以将其至多X张牌扣置于其武将牌旁（X为其体力值），当前回合结束后，该角色获得这些牌。当你使用【杀】对手牌数与装备区里牌数均不大于你的角色造成伤害时，此伤害+1。",
	["mobilepojun_num"] = "请选择“破军”移除的牌数",
	["mobilepojun_dis"] = "请选择“破军”移除的牌",
	["#MobilepojunDamage"] = "%from 的“<font color=\"yellow\"><b>破军</b></font>”被触发，对 %to 的伤害由 %arg 点增加至 %arg2 点",
	
	["mobile_wuguotai"] = "手杀界吴国太",
	["&mobile_wuguotai"] = "界吴国太",
	["illustrator:mobile_wuguotai"] = "李秀森",
	["mobileganlu"] = "甘露",
	[":mobileganlu"] = "出牌阶段限一次，你可以选择两名装备区里的牌数之差不大于X的角色（X为你已损失的体力值），交换其装备区里的牌；若你选择的角色中含有你，不受牌数之差的限制。",
	
	["mobile_yujin"] = "手杀界于禁",
	["&mobile_yujin"] = "界于禁",
	["illustrator:mobile_yujin"] = "biou09",
	["mobilejieyue"] = "节钺",
	[":mobilejieyue"] = "结束阶段开始时，你可以交给一名其他角色一张牌，然后其选择一项：保留一张手牌和一张装备区内的牌，弃置其余的牌；或令你摸三张牌。",
	["mobilejieyue-invoke"] = "你可以发动“节钺”交给一名其他角色一张牌",
	["@mobilejieyue"] = "请选择需要保留的手牌和装备区的牌，否则 %src 摸三张牌",
	["~mobilejieyue"] = "选择需要保留的牌→点“确定”",
	
	["mobile_liaohua"] = "手杀界廖化",
	["&mobile_liaohua"] = "界廖化",
	["illustrator:mobile_liaohua"] = "",
	["mobiledangxian"] = "当先",
	[":mobiledangxian"] = "锁定技，回合开始时，你获得弃牌堆内的一张【杀】并执行一个额外的出牌阶段。",
	["mobilefuli"] = "伏枥",
	[":mobilefuli"] = "限定技，当你处于濒死状态时，你可以将体力回复至X点（X为全场势力数）。然后若你的体力值为全场唯一最高，你将武将牌翻面。",
	
	["mobile_bulianshi"] = "手杀界步练师",
	["&mobile_bulianshi"] = "界步练师",
	["illustrator:mobile_bulianshi"] = "",
	["mobileanxu"] = "安恤",
	[":mobileanxu"] = "出牌阶段限一次，你可以令一名其他角色获得另一名其他角色的一张牌。若其获得的是手牌，你摸一张牌。一名角色以此法获得另一名角色的牌后，你可以令其中手牌较少的角色摸一张牌。",
	
	["mobile_liubiao"] = "手杀界刘表",
	["&mobile_liubiao"] = "界刘表",
	["illustrator:mobile_liubiao"] = "",
	["mobilezongshi"] = "宗室",
	[":mobilezongshi"] = "锁定技，你的手牌上限+X（X为全场势力数）。准备阶段开始时，若你的手牌数大于你的体力值，你本回合使用【杀】无次数限制。",
	
	["mobile_gongsunzan"] = "手杀界公孙瓒",
	["&mobile_gongsunzan"] = "界公孙瓒",
	["illustrator:mobile_gongsunzan"] = "",
	["mobileyicong"] = "义从",
	[":mobileyicong"] = "锁定技，你与其他角色的距离-X（X为你的体力值-1，且至少为0）；其他角色与你的距离+Y（Y为你已损失的体力值-1，且至少为0）。",
	
	["mobile_lingtong"] = "手杀界凌统",
	["&mobile_lingtong"] = "界凌统",
	["illustrator:mobile_lingtong"] = "青岛磬蒲",
	["mobilexuanfeng"] = "旋风",
	[":mobilexuanfeng"] = "当你于弃牌阶段弃置过至少两张牌，或当你失去装备区内的牌后，你可以选择一项：弃置至多两名其他角色的共计两张牌；或将一名其他角色装备区内的一张牌移至另一名其他角色的装备区。",
	["mobilexuanfeng:discard"] = "弃置至多两名其他角色的共计两张牌",
	["mobilexuanfeng:move"] = "移动装备牌",
	
	["mobile_caozhi"] = "手杀界曹植",
	["&mobile_caozhi"] = "界曹植",
	["illustrator:mobile_caozhi"] = "青岛磬蒲",
	["mobilejiushi"] = "酒诗",
	[":mobilejiushi"] = "若你的武将牌正面朝上，你可以将武将牌翻面，视为使用一张【酒】。当你受到伤害后，若你的武将牌背面朝上，你可以将武将牌翻面，然后获得牌堆中随机的一张锦囊牌。",
	[":mobilejiushi2"] = "若你的武将牌正面朝上，你可以将武将牌翻面，视为使用一张【酒】。当你受到伤害后，若你的武将牌背面朝上，你可以将武将牌翻面。当你的武将牌翻面时，你获得牌堆中随机的一张锦囊牌。",
	["mobilechengzhang"] = "成章",
	[":mobilechengzhang"] = "觉醒技，准备阶段开始时，若你造成伤害与受到伤害之和不小于7，你回复1点体力，摸一张牌，然后升级“酒诗”。",
	["#MobilechengzhangWake"] = "%from 造成和受到伤害之和为 %arg，触发“%arg2”觉醒",

	["mobile_handang"] = "手杀界韩当",
	["&mobile_handang"] = "界韩当",
	["illustrator:mobile_handang"] = "monkey",
	["mobilegongqi"] = "弓骑",
	[":mobilegongqi"] = "出牌阶段限一次，你可以弃置一张非基本牌并弃置一名其他角色的一张牌；若你的装备区内有坐骑牌，你的攻击范围无限。",
	
	["mobile_zhonghui"] = "手杀界钟会",
	["&mobile_zhonghui"] = "界钟会",
	["illustrator:mobile_zhonghui"] = "monkey",
	["mobilequanji"] = "权计",
	[":mobilequanji"] = "出牌阶段结束时，若你的手牌数大于体力值，或当你受到1点伤害后，你可以摸一张牌，然后将一张手牌置于武将牌上，称为“权”；你的手牌上限+X（X为“权”的数量）。",
	
	["mobile_chengpu"] = "手杀界程普",
	["&mobile_chengpu"] = "界程普",
	["illustrator:mobile_chengpu"] = "monkey",
	["mobilelihuo"] = "疠火",
	[":mobilelihuo"] = "当你使用普通【杀】时，你可以将此【杀】改为火【杀】，若此【杀】的目标处于“连环状态”，此【杀】造成的伤害+1；当你使用的火【杀】结算完后，此【杀】每造成2点伤害，你失去1点体力。",
	
	["mobile_yufan"] = "手杀界虞翻",
	["&mobile_yufan"] = "界虞翻",
	["illustrator:mobile_yufan"] = "",
	["mobilezongxuan"] = "纵玄",
	[":mobilezongxuan"] = "出牌阶段限一次，你可以摸一张牌，然后将一张牌置于牌堆顶；当你的牌因弃置而置入弃牌堆后，你可以将其中任意张牌置于牌堆顶。",
	["mobilezongxuan-put"] = "请将一张牌置于牌堆顶",
	["@mobilezongxuan"] = "你可以将其中任意张牌置于牌堆顶",
	["~mobilezongxuan"] = "选择若干张牌→点“确定”",
	["#mobilezongxuan"] = "纵玄",
	
	["mobile_manchong"] = "手杀界满宠",
	["&mobile_manchong"] = "界满宠",
	["illustrator:mobile_manchong"] = "",
	["mobilejunxing"] = "峻刑",
	[":mobilejunxing"] = "出牌阶段限一次，你可以弃置任意张手牌并令一名其他角色选择一项：弃置等量的牌并失去1点体力；将武将牌翻面，然后摸等量的牌。",

	["mobile_liru"] = "手杀界李儒",
	["&mobile_liru"] = "界李儒",
	["illustrator:mobile_liru"] = "",
	["mobilejuece"] = "绝策",
	[":mobilejuece"] = "结束阶段开始时，你可以对本回合失去过牌的一名其他角色造成1点伤害。",
	["@mobilejuece"] = "你可以对本回合失去过牌的一名其他角色造成1点伤害",
	["mobilemieji"] = "灭计",
	[":mobilemieji"] = "出牌阶段限一次，你可以展示一张黑色锦囊牌并将之置于牌堆顶并令一名有牌的其他角色选择一项：交给你一张锦囊牌；或弃置两张非锦囊牌。",
	["@mobilemieji"] = "请交给 %src 一张锦囊牌，或弃置两张非锦囊牌",
	["~mobilemieji"] = "选择合适的牌→点“确定”",
	["@mobilemieji_nottrick"] = "请弃置两张非锦囊牌",
	["@mobilemieji_trick"] = "请交给 %src 一张锦囊牌",

	["mobile_gaoshun"] = "手杀界高顺",
	["&mobile_gaoshun"] = "界高顺",
	["illustrator:mobile_gaoshun"] = "蛋费鸡丁",
	["mobilexianzhen"] = "陷阵",
	[":mobilexianzhen"] = "出牌阶段限一次，你可以与一名角色拼点，若你：赢，此阶段你无视该角色的防具，对其使用牌无距离和次数限制；没赢，此阶段你不能使用【杀】。若你发动“陷阵”拼点的牌为【杀】，本回合你的【杀】不计入手牌上限。",
	["mobilejinjiu"] = "禁酒",
	[":mobilejinjiu"] = "锁定技，你的【酒】视为【杀】；当你受到【酒】【杀】的伤害时，此伤害-X（X为增加此【杀】伤害的【酒】的数量）；你的回合内，其他角色不能使用【酒】。",
	["#MobilejinjiuReduce"] = "%from 的“%arg”被触发，伤害减为了 %arg2 点",
	["#MobilejinjiuPrevent"] = "%from 的“%arg”被触发，防止了 %arg2 点伤害",
	
	["mobile_jianyong"] = "手杀界简雍",
	["&mobile_jianyong"] = "界简雍",
	["illustrator:mobile_jianyong"] = "",
	["mobileqiaoshui"] = "巧说",
	[":mobileqiaoshui"] = "出牌阶段限一次，你可以与一名角色拼点，若你：赢，本阶段你使用的下一张基本牌或非延时类锦囊牌可以多选择或少选择一个目标（无距离限制）；没赢，本阶段你不能使用锦囊牌。",
	["mobileqiaoshui:add"] = "增加一名目标",
	["mobileqiaoshui:remove"] = "减少一名目标",
	["mobilezongshih"] = "纵适",
	[":mobilezongshih"] = "当你拼点后，你可以观看牌堆顶的一张牌，且可以选择一项：获得此牌；或获得拼点牌中点数较小的一张。",
	["#mobilezongshih_draw"] = "牌堆顶",
	["#mobilezongshih_pindian"] = "拼点牌",
	["@mobilezongshih"] = "你可以获得其中一张牌",
	["~mobilezongshih"] = "选择一张牌→点“确定”",
	
	["mobile_zhuran"] = "手杀界朱然",
	["&mobile_zhuran"] = "界朱然",
	["illustrator:mobile_zhuran"] = "",
	["mobiledanshou"] = "胆守",
	[":mobiledanshou"] = "其他角色的结束阶段开始时，若你本回合成为其使用牌的目标的次数：等于0，你摸一张牌；大于0，你可以弃置等量张牌对其造成1点伤害。",
	["@mobiledanshou-dis"] = "你可以弃置 %arg 张牌对 %src 造成1点伤害",
	
	["mobile_panzhangmazhong"] = "手杀界潘璋＆马忠",
	["&mobile_panzhangmazhong"] = "界潘璋马忠",
	["illustrator:mobile_panzhangmazhong"] = "",
	["mobileduodao"] = "夺刀",
	[":mobileduodao"] = "当你受到伤害后，你可以获得伤害来源装备区里的武器牌。",
	["mobileanjian"] = "暗箭",
	[":mobileanjian"] = "锁定技，当你使用【杀】指定目标后，若你不在其攻击范围内，你选择一项：令其无法响应此【杀】；或其受到此【杀】造成的伤害+1。",
	["mobileanjian:noresponse"] = "其无法响应此【杀】",
	["mobileanjian:damage"] = "此【杀】造成的伤害+1",
	
	["mobile_fuhuanghou"] = "手杀界伏皇后",
	["&mobile_fuhuanghou"] = "界伏皇后",
	["illustrator:mobile_fuhuanghou"] = "",
	["mobilezhuikong"] = "惴恐",
	[":mobilezhuikong"] = "每轮限一次，其他角色的回合开始时，若其体力值不小于你，你可与其拼点，若你：赢，其本回合无法使用牌指定除其以外的角色为目标；没赢，你获得其拼点的牌，然后其视为对你使用一张【杀】。",
	["mobileqiuyuan"] = "求援",
	[":mobileqiuyuan"] = "当你成为【杀】的目标时，你可以令另一名其他角色选择一项：交给你一张除【杀】以外的基本牌；或成为此【杀】的目标。",
	["@mobileqiuyuan-invoke"] = "你可以发动“求援”",
	["@mobileqiuyuan-give"] = "请交给 %src 一张除【杀】以外的基本牌，否则你也成为此【杀】的目标",
	
	["mobile_guohuai"] = "手杀界郭淮",
	["&mobile_guohuai"] = "界郭淮",
	["illustrator:mobile_guohuai"] = "",
	["mobilejingce"] = "精策",
	[":mobilejingce"] = "结束阶段开始时，若此回合内因使用或打出而置入弃牌堆的牌数量不小于你的体力值，你可以摸两张牌。",
	
	["mobile_chenqun"] = "手杀界陈群",
	["&mobile_chenqun"] = "界陈群",
	["illustrator:mobile_chenqun"] = "",
	["mobiledingpin"] = "定品",
	[":mobiledingpin"] = "出牌阶段，你可以弃置一张牌（不能是你本回合使用或弃置过的类型）并令一名角色进行一次判定，若判定结果为：黑色，该角色摸X张牌（X为该角色的体力值且至多为3），然后你于此回合内不能再对其发动此技能；"..
						"红桃，你此次弃置的牌不计入弃置过的类型；方块，你将武将牌翻面。",
	
	["mobile_zhoucang"] = "手杀界周仓",
	["&mobile_zhoucang"] = "界周仓",
	["illustrator:mobile_zhoucang"] = "",
	["mobilezhongyong"] = "忠勇",
	[":mobilezhongyong"] = "当你于出牌阶段内使用的【杀】结算完时，若没有目标角色使用【闪】响应此【杀】，你可以获得此【杀】；若有目标角色使用【闪】响应此【杀】，你可以选择一项：" ..
					"获得响应的【闪】，然后你可以将此【杀】交给不为此【杀】目标的一名其他角色；或将响应的【闪】交给不为此【杀】目标的一名其他角色，然后你本回合获得以下效果：" ..
					"可以额外使用一张【杀】、使用的下一张【杀】造成的伤害+1。本回合你不能使用通过此技能获得的牌。",
	["@mobilezhongyong-invoke"] = "你可以获得响应的【闪】，或交出响应的【闪】",
	["@mobilezhongyong-give"] = "你可以将此【杀】交给不为此【杀】目标的一名其他角色",
	[":&mobilezhongyong"] = "本回合可以额外使用%src张【杀】、使用的下一张【杀】造成的伤害+%src",

	["mobile_guyong"] = "手杀界顾雍",
	["&mobile_guyong"] = "界顾雍",
	["illustrator:mobile_guyong"] = "",
	["mobileshenxing"] = "慎行",
	[":mobileshenxing"] = "<font color=\"green\"><b>出牌阶段限X次，</b></font>你可以弃置两张牌，若这两张牌颜色：不同，你摸两张牌；相同，你摸一张牌（X为你的体力值）。",
	["mobilebingyi"] = "秉壹",
	[":mobilebingyi"] = "结束阶段开始时，你可以展示所有手牌，若所有手牌颜色相同或类型相同，你令至多X名角色摸一张牌（X为你的手牌数）。",
	["@mobilebingyi"] = "你可以展示所有手牌发动“秉壹”",
	["~mobilebingyi"] = "若手牌均为同一颜色或同一类型，选择至多X名角色→点击“确定”；否则直接点击“确定”",
	
	["mobile_caifuren"] = "手杀界蔡夫人",
	["&mobile_caifuren"] = "界蔡夫人",
	["illustrator:mobile_caifuren"] = "",
	["mobileqieting"] = "窃听",
	[":mobileqieting"] = "其他角色的回合结束时，若其此回合没有对其他角色造成过伤害，你可以选择一项：观看其两张手牌并获得其中一张牌；或将其装备区内一张牌置入你的装备区；或摸一张牌。",
	["mobileqieting:view"] = "观看%src两张手牌，获得其中一张",
	["mobileqieting:move"] = "将%src装备区内的一张牌移给自己",
	["mobileqieting:draw"] = "摸一张牌",
	
	["mobile_jushou"] = "手杀界沮授",
	["&mobile_jushou"] = "界沮授",
	["#mobile_jushou"] = "监军谋国",
	["illustrator:mobile_jushou"] = "",
	["mobilejianying"] = "渐营",
	[":mobilejianying"] = "当你于出牌阶段内使用牌时，若此牌与你本阶段使用的上一张牌花色或点数相同，你可以摸一张牌。出牌阶段限一次，你可以将一张牌当任意一张无次数限制的基本牌使用，" ..
							"若你于本回合使用的上一张牌有花色，此牌视为该花色。",
	
	["mobile_sunxiu"] = "手杀界孙休",
	["&mobile_sunxiu"] = "界孙休",
	["illustrator:mobile_sunxiu"] = "",
	["mobileyanzhu"] = "宴诛",
	[":mobileyanzhu"] = "出牌阶段限一次，你可以令一名其他角色选择一项：令你获得其装备区里所有的牌，然后你失去“宴诛”并升级“兴学”；或令你获得其区域内的一张牌。",
	["mobileyanzhu:equip"] = "令%src获得你装备区里所有的牌，然后其失去“宴诛”并升级“兴学”",
	["mobileyanzhu:obtain"] = "令%src获得你区域内的一张牌",
	["mobilexingxue"] = "兴学",
	[":mobilexingxue"] = "结束阶段开始时，你可以令至多X名角色依次摸一张牌并将一张牌置于牌堆顶（X为你的体力值）。",
	[":mobilexingxue1"] = "结束阶段开始时，你可以令至多X名角色依次摸一张牌并将一张牌交给一名被“兴学”选择的角色或置于牌堆顶（X为你的体力上限）。",
	["@mobilexingxue"] = "你可以对至多%src名角色发动“兴学”",
	["mobilexingxue:give"] = "将一张牌交给一名被“兴学”选择的角色",
	["mobilexingxue:put"] = "将一张牌置于牌堆顶",
}