-- translation for MobileZhi Package

return {
	["mobilezhi"] = "手杀智包",
	
	["mobilezhi_wangcan"] = "王粲",
	["#mobilezhi_wangcan"] = "词章纵横",
	["illustrator:mobilezhi_wangcan"] = "",
	["mobilezhiqiai"] = "七哀",
	[":mobilezhiqiai"] = "出牌阶段限一次，你可以将一张非基本牌交给一名其他角色，令其选择一项：你回复1点体力；或你摸两张牌。",
	["mobilezhiqiai:recover"] = "其回复1点体力",
	["mobilezhiqiai:draw"] = "其摸两张牌",
	["mobilezhishanxi"] = "善檄",
	[":mobilezhishanxi"] = "出牌阶段开始时，你可以令一名没有“檄”标记的其他角色获得一枚“檄”标记（若场上有“檄”标记，改为转移给该角色）。当拥有“檄”标记的角色回复体力后，若其未处于濒死状态，其选择一项：交给你两张牌；或失去1点体力。",
	["mobilezhixi"] = "檄",
	["@mobilezhishanxi-invoke"] = "你可以令一名没有“檄”标记的其他角色获得一枚“檄”标记",
	["mobilezhishanxi-give"] = "请交给 %src 两张牌，否则你失去1点体力",
	
	["mobilezhi_bianfuren"] = "卞夫人",
	["#mobilezhi_bianfuren"] = "内助贤后",
	["illustrator:mobilezhi_bianfuren"] = "",
	["mobilezhiwanwei"] = "挽危",
	[":mobilezhiwanwei"] = "每轮限一次，你可令进入濒死状态的其他角色或出牌阶段你可令一名其他角色回复X+1点体力，然后你失去X点体力（X为你的体力值）。",
	["mobilezhiyuejian"] = "约俭",
	[":mobilezhiyuejian"] = "你的手牌上限等于体力上限；当你进入濒死状态时，你可以弃置两张牌，然后回复1点体力。",
	["@mobilezhiyuejian"] = "你可以弃置两张牌，然后回复1点体力",
	
	["mobilezhi_chenzhen"] = "陈震",
	["#mobilezhi_chenzhen"] = "歃盟使节",
	["illustrator:mobilezhi_chenzhen"] = "",
	["mobilezhishameng"] = "歃盟",
	[":mobilezhishameng"] = "出牌阶段限一次，你可以弃置两张颜色相同的手牌并令一名其他角色摸两张牌，然后你摸三张牌。",
	
	["mobilezhi_feiyi"] = "费祎",
	["#mobilezhi_feiyi"] = "蜀汉名相",
	["illustrator:mobilezhi_feiyi"] = "",
	["mobilezhijianyu"] = "谏喻",
	[":mobilezhijianyu"] = "每轮限一次，出牌阶段，你可以选择两名角色，直到你的下回合开始，当其中一名角色于其出牌阶段内使用牌指定另一名角色为目标时，你令后者摸一张牌。",
	["mobilezhishengxi"] = "生息",
	[":mobilezhishengxi"] = "结束阶段开始时，若你于本回合内未造成过伤害，你可以摸两张牌。",
	
	["second_mobilezhi_feiyi"] = "费祎-第二版",--shu 3
	["&second_mobilezhi_feiyi"] = "费祎",
	["#second_mobilezhi_feiyi"] = "洞世丞相",
	["illustrator:second_mobilezhi_feiyi"] = "",
	["secondmobilezhishengxi"] = "生息",
	[":secondmobilezhishengxi"] = "结束阶段开始时，若你于本回合内使用过牌且未造成过伤害，你可以从游戏外或牌堆中获得一张【调剂盐梅】或【无中生有】或【无懈可击】或【过河拆桥】。",
	["secondmobilezhikuanji"] = "宽济",
	[":secondmobilezhikuanji"] = "每个回合限一次，当你的牌因弃置而置入弃牌堆后，你可令一名其他角色获得其中一张牌，然后你摸一张牌。",
	
	["mobilezhi_sunshao"] = "孙邵",
	["#mobilezhi_sunshao"] = "弼政之功",
	["illustrator:mobilezhi_sunshao"] = "",
	["mobilezhifubi"] = "辅弼",
	[":mobilezhifubi"] = "游戏开始时，你可以令一名其他角色获得一枚“辅”标记。拥有“辅”标记的角色手牌上限+3。",
	["@mobilezhifubi-invoke"] = "你可以令一名其他角色获得一枚“辅”标记",
	["mobilezhifu"] = "辅",
	["mobilezhizuici"] = "罪辞",
	[":mobilezhizuici"] = "当你进入濒死状态时，你可以废除你一个有装备的装备栏，然后将体力回复至1点。",
	["mobilezhizuici:0"] = "废除武器栏",
	["mobilezhizuici:1"] = "废除防具栏",
	["mobilezhizuici:2"] = "废除+1坐骑栏",
	["mobilezhizuici:3"] = "废除-1坐骑栏",
	["mobilezhizuici:4"] = "废除宝物栏",
	
	["second_mobilezhi_sunshao"] = "孙邵-第二版",
	["&second_mobilezhi_sunshao"] = "孙邵",
	["#second_mobilezhi_sunshao"] = "弼政之功",
	["illustrator:second_mobilezhi_sunshao"] = "",
	["secondmobilezhifubi"] = "辅弼",
	[":secondmobilezhifubi"] = "游戏开始时，你可以令一名其他角色获得一枚“辅”标记。拥有“辅”标记的角色出牌阶段开始时，你可以选择一项：令其本回合手牌上限+3；或令其此阶段使用【杀】的次数上限+1。",
	["secondmobilezhifubi:max"] = "令其本回合手牌上限+3",
	["secondmobilezhifubi:slash"] = "令其此阶段使用【杀】的次数上限+1",
	["secondmobilezhizuici"] = "罪辞",
	[":secondmobilezhizuici"] = "出牌阶段或当你进入濒死状态时，你可以废除你一个有装备的装备栏，回复2点体力，然后你可以转移“辅”标记。",
	["@secondmobilezhizuici"] = "你可以转移“辅”标记",
	["secondmobilezhizuici:0"] = "废除武器栏",
	["secondmobilezhizuici:1"] = "废除防具栏",
	["secondmobilezhizuici:2"] = "废除+1坐骑栏",
	["secondmobilezhizuici:3"] = "废除-1坐骑栏",
	["secondmobilezhizuici:4"] = "废除宝物栏",
	
	["third_mobilezhi_sunshao"] = "孙邵-第三版",
	["&third_mobilezhi_sunshao"] = "孙邵",
	["#third_mobilezhi_sunshao"] = "弼政之功",
	["illustrator:third_mobilezhi_sunshao"] = "",
	["thirdmobilezhifubi"] = "辅弼",
	[":thirdmobilezhifubi"] = "游戏开始时，你可以令一名其他角色获得一枚“辅”标记。拥有“辅”标记的角色准备阶段开始时，你可以选择一项：令其本回合手牌上限+3；或令其此阶段使用【杀】的次数上限+1。",
	["thirdmobilezhifubi:max"] = "令其本回合手牌上限+3",
	["thirdmobilezhifubi:slash"] = "令其此阶段使用【杀】的次数上限+1",
	
	["fourth_mobilezhi_sunshao"] = "孙邵-第四版",--wu 3
	["&fourth_mobilezhi_sunshao"] = "孙邵",
	["#fourth_mobilezhi_sunshao"] = "创基抉政",
	["illustrator:fourth_mobilezhi_sunshao"] = "",
	["fourthmobilezhidingyi"] = "定仪",
	[":fourthmobilezhidingyi"] = "游戏开始时，你令所有角色获得你选择的一项效果：摸牌阶段额外摸一张牌；或手牌上限+2；或攻击范围+1；或脱离濒死状态后回复1点体力。",
	["fourthmobilezhizuici"] = "罪辞",
	[":fourthmobilezhizuici"] = "当你受到伤害后，你可以令伤害来源失去“定仪”效果，然后你令其从牌堆中获得一张你选择的：【无中生有】或【无懈可击】或【过河拆桥】。",
	["fourthmobilezhifubi"] = "辅弼",
	[":fourthmobilezhifubi"] = "每轮限一次，出牌阶段，你可以选择一名角色并选择一项：更换其“定仪”效果；或弃置一张牌，令其“定仪”效果数值翻倍，直到新的一轮你的回合开始。",
	
	["mobilezhi_luotong"] = "骆统",
	["#mobilezhi_luotong"] = "力政人臣",
	["illustrator:mobilezhi_luotong"] = "",
	["mobilezhiqinzheng"] = "勤政",
	[":mobilezhiqinzheng"] = "锁定技，你每使用或打出：三张牌，你从牌堆随机获得一张【杀】或【闪】；五张牌，你从牌堆随机获得一张【桃】或【酒】；八张牌，你从牌堆随机获得一张【无中生有】或【决斗】。",
	
	["mobilezhi_xunchen"] = "荀谌",
	["#mobilezhi_xunchen"] = "谋识无对",
	["illustrator:mobilezhi_xunchen"] = "",
	["mobilezhiduoji"] = "夺冀",
	[":mobilezhiduoji"] = "限定技，出牌阶段，你可以弃置两张手牌并选择一名装备区有牌的其他角色，你获得其装备区内所有牌。",
	["mobilezhijianzhan"] = "谏战",
	[":mobilezhijianzhan"] = "出牌阶段限一次，你可以令一名其他角色选择一项：视为对其攻击范围内你选择的一名手牌比其少的角色使用一张【杀】；或令你摸一张牌。",
	["mobilezhijianzhan:slash"] = "视为使用【杀】",
	["mobilezhijianzhan:draw"] = "其摸一张牌",
	["@mobilezhijianzhan-slash"] = "请选择 %src 使用【杀】的目标",
	
	["second_mobilezhi_xunchen"] = "荀谌-第二版",
	["&second_mobilezhi_xunchen"] = "荀谌",
	["#second_mobilezhi_xunchen"] = "谋识无对",
	["illustrator:second_mobilezhi_xunchen"] = "",
	["secondmobilezhiduoji"] = "夺冀",
	[":secondmobilezhiduoji"] = "出牌阶段限一次，你可以将一张牌置于一名其他角色的武将牌上，称为“冀”。拥有“冀”的角色使用的装备牌结算完后，你获得之，然后其将一张“冀”置入弃牌堆并摸一张牌。拥有“冀”的角色回合结束时，其将武将牌上的“冀”置入弃牌堆，然后你获得之。",
	["smzdjji"] = "冀",
	["@secondmobilezhiduoji"] = "请将一张“冀”置入弃牌堆",
	
	["third_mobilezhi_xunchen"] = "荀谌-第三版",--qun 3
	["&third_mobilezhi_xunchen"] = "荀谌",
	["#third_mobilezhi_xunchen"] = "谋刃略锋",
	["illustrator:third_mobilezhi_xunchen"] = "",
	["thirdmobileweipo"] = "危迫",
	[":thirdmobileweipo"] = "出牌阶段限一次，你可以选择一名角色并选择一个牌名：【兵临城下】、【无中生有】、【无懈可击】、【过河拆桥】，然后其获得一枚“危迫”标记。回合开始时，你弃置场上所有的“危迫”标记。" ..
						"拥有“危迫”标记的角色的出牌阶段，其可以弃置一枚“危迫”标记，将一张【杀】当你选择的牌使用。",
	["thirdmobilechenshi"] = "陈势",
	[":thirdmobilechenshi"] = "当其他角色使用【兵临城下】指定目标后，其可以交给你一张牌，然后将牌堆顶三张牌中不为【杀】的牌置入弃牌堆。" ..
						"当其他角色成为【兵临城下】的目标后，其可以交给你一张牌，然后将牌堆顶三张牌中的【杀】置入弃牌堆。",
	["thirdmobilemoushi"] = "谋识",
	[":thirdmobilemoushi"] = "锁定技，当你受到伤害时，若造成伤害的牌与上次对你造成伤害的牌颜色相同，防止此伤害。",
	
	["mobilezhi_duyu"] = "杜预",
	["#mobilezhi_duyu"] = "文成武德",
	["illustrator:mobilezhi_duyu"] = "",
	["mobilezhiwuku"] = "武库",
	[":mobilezhiwuku"] = "锁定技，当一名角色使用装备牌时，你获得一枚“武库”标记（数量至多为3）。",
	["mobilezhisanchen"] = "三陈",
	[":mobilezhisanchen"] = "觉醒技，结束阶段开始时，若你有至少三枚“武库”标记，你加1点体力上限，回复1点体力，然后获得技能“灭吴”。",
	["#MobileZhiSanchenWake"] = "%from 的“<font color=\"yellow\"><b>武库</b></font>”标记数为 %arg，触发“%arg2”觉醒",
	["mobilezhimiewu"] = "灭吴",
	[":mobilezhimiewu"] = "每个回合限一次，你可以弃置一枚“武库”标记，将一张牌当一张基本牌或锦囊牌使用或打出，然后你摸一张牌。",
	["mobilezhimiewu_saveself"] = "“灭吴”【桃】或【酒】",
	["mobilezhimiewu_slash"] = "“灭吴”【杀】",
}
	